### ISSUE TITLE
Docstrings aren't using standard formatting

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#100]
We should learn to write docstrings that adhere more to standard python documentation and produce useful html documentation.
Here's an example from xarray:
https://github.com/pydata/xarray/blob/master/xarray/core/dataarray.py#L163

Probably we should adopt the PEP 257 standard:
https://www.python.org/dev/peps/pep-0257/

**Comment by xylar** [comment]
Okay, it looks a little more complicated than I thought initially.  We want to write good docstrings to help us with documentation later, but there's not really a "standard" procedure.  Instead, we'd want to adopt a set of conventions.  Even that doesn't seem super easy to come by.

My guess is we'd want to use sphinx to generate our documentation.  Even then, there's a lot of flexibility.  But I like how `xarray`'s documentation looks so maybe we could try to mimic their style.

Here's a bit more info on docstring for sphinx:
https://pythonhosted.org/an_example_pypi_project/sphinx.html

**Comment by milenaveneziani** [comment]
@xylar: would you consider this solved after #158 is merged?

**Comment by xylar** [comment]
No, unfortunately not.  This is something I'll fix as soon as I have time.  But there are quite a number of old, bad docstrings lying around.  Let's leave the issue open for now.

**Comment by xylar** [comment]
Should finally be getting addressed by #277

**Comment by milenaveneziani** [comment]
Final clean up for this done in #277.
