### ISSUE TITLE
divide by zero in SSS climatology analysis

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#101]
Each time running `ocean/modelvsobs.py` on `'SSS'`, I see:
```
Plotting 2-d maps of SSS climatologies...
Reading files /media/xylar/extra_data/data_overflow/analysis/GMPAS-QU240/run/mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through /media/xylar/extra_data/data_overflow/analysis/GMPAS-QU240/run/mpaso.hist.am.timeSeriesStatsMonthly.0002-12-01.nc
/home/xylar/anaconda2/envs/default/lib/python2.7/site-packages/dask/array/numpy_compat.py:45: RuntimeWarning: invalid value encountered in divide
  x = np.divide(x1, x2, out)
```

I am not sure of this but I suspect there's a divide by zero happening.

I'm testing on a small (G240km) run from the config_reorg branch, but I don't think this issue is specific to a given analysis or a given branch.

It is also not a top priority to fix, just something that makes it look like something might be wrong.

**Comment by vanroekel** [comment]
@xylar could you point me to your reproducer branch?  I've seen this, but pulling things from dask space to numpy space fixed the issue, in this line here from ocean/modelvsobs.py

https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/ocean/ocean_modelvsobs.py#L155-L157

```
        # The following line converts from DASK to numpy to supress an odd
        # warning that doesn't influence the figure output
        ds_tslice.SSS.values
```

So if you have a case I can use, I'll dig into this.

**Comment by vanroekel** [comment]
@xylar I should also clarify that I haven't seen this error with the bit of code above included in all of my tests and plots, but my branch may have diverged enough from develop to miss this.

**Comment by xylar** [comment]
Thanks for getting back to me @vanroekel.  I can't reproduce the warning on LANL IC so it may be something related to the newer versions of xarray, dask, etc. that I have on my laptop.

If I ever see it somewhere other than my laptop, I'll reopen this issue but I'll close it for now.

**Comment by vanroekel** [comment]
@xylar I've been using the analysis repo on anvil (ACME nodes on blues machine at argonne) and have seen the error emerge again.  Comparing the conda environment between anvil and LANL IC, there are new versions of dask and xarray.  So I suspect your hunch is correct, and perhaps we should reopen this.  Although I will say that this doesn't seem to be a serious issue as the plots are still look as expected, even with the RunTimeWarning

**Comment by xylar** [comment]
Eh, I'm fine either way.  If you want to track down what's causing this sometime, go ahead and reopen the issue.  If you're fine with getting a seemingly harmless warning, I'm okay with it, too.  Given how much garbage gets dumped to stdout by ncremap, no one is likely to notice...

**Comment by vanroekel** [comment]
I really don't want to spend time on this if you are fine with it.  I'd say we leave it alone unless someone on the coupled team sees it and is concerned by it.
