### ISSUE TITLE
Provide user-friendly examples of analysis tools

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#11]
To facilitate contributions from developers with less python experience to the analysis framework, well documented examples of analyses tools including required inputs and outputs and adhering to the language standards should be provided.

**Comment by milenaveneziani** [comment]
@xylar, @pwolfram: can we considered this issue solved?

**Comment by xylar** [comment]
Yes, I hope so.

**Comment by pwolfram** [comment]
To be clear-- how do we gauge success here?  For example, are we 100% confident that the system is "user-friendly"?  It seems to me that as the developers of this framework that this is not something we can necessarily decide ourselves-- our users would have to (agree / disagree) to know for sure if we have met this metric.

**Comment by xylar** [comment]
But this also suggests that having an open issue for a vague concept like
this is unlikely to be useful.

**Comment by milenaveneziani** [comment]
I agree. We provided what we think are user friendly examples: we can open more specific issues if/when we hear back from users.

**Comment by milenaveneziani** [comment]
seems like we had forgotten to close this..
