### ISSUE TITLE
Cleanup hard-coded constants

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#113]
There are several places where constants are hard-coded in scripts, e.g.,

 * https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/sea_ice/modelvsobs.py#L104
* https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/sea_ice/modelvsobs.py#L179
 * https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/sea_ice/timeseries.py#L180
 * https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/sea_ice/timeseries.py#L195

These constants should be moved to a file like https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/shared/constants/constants.py

**Comment by xylar** [comment]
Should be addressed by #117

**Comment by xylar** [comment]
Closed via #117
