### ISSUE TITLE
Config error when running for sea ice standalone.

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#116]
While attempting to run the sea ice diagnostics for a standalone sea ice script I seem to get a config error that seems to be a missing config entry:

[akt@wf-fe1 MPAS-Analysis]$ run_analysis.py ./configs/lanl/config.20170207.MPAS-SeaIce.QU60km_polar.wolf

Plotting sea-ice area and volume time series...
Reading files /net/scratch2/akt/MPAS/rundirs/rundir_QU60km_polar/analysis_members/timeSeriesStatsMonthly.1959-12.nc through /net/scratch2/akt/MPAS/rundirs/rundir_QU60km_polar/analysis_members/timeSeriesStatsMonthly.1962-01.nc
  Load sea-ice data...
   Warning: Preprocessed time series ends before the timeSeries startYear and will not be plotted.
  Compute NH and SH time series of iceAreaCell...
  Make plots...
  Compute NH and SH time series of iceVolumeCell...
  Make plots...

Plotting 2-d maps of sea-ice concentration and thickness climatologies...
Reading files /net/scratch2/akt/MPAS/rundirs/rundir_QU60km_polar/analysis_members/timeSeriesStatsMonthly.1959-12.nc through /net/scratch2/akt/MPAS/rundirs/rundir_QU60km_polar/analysis_members/timeSeriesStatsMonthly.1962-01.nc

Climatology directory does not exist. Create it...

Regridded directory does not exist. Create it...

Traceback (most recent call last):
  File "run_analysis.py", line 259, in <module>
    analysis(config)
  File "run_analysis.py", line 226, in analysis
    variableMap=seaIceVariableMap)
  File "/turquoise/usr/projects/climate/akt/diagnostics/MPAS-Analysis/mpas_analysis/sea_ice/modelvsobs.py", line 118, in seaice_modelvsobs
    'concentrationNASATeamNH_JFM')
  File "/turquoise/usr/projects/climate/akt/diagnostics/MPAS-Analysis/mpas_analysis/shared/io/utility.py", line 44, in buildConfigFullPath
    config.get(section, relativePathOption))
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/default-2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'concentrationnasateamnh_jfm' in section: 'seaIceObservations'

**Comment by akturner** [comment]
I know what the problem is so I'll assign myself to fix it. I can't add labels or assign people I guess because I'm not an maintainer??

**Comment by milenaveneziani** [comment]
I just added you, @akturner.

**Comment by xylar** [comment]
Fixed with #115.

**Comment by xylar** [comment]
@akturner, I've added you as a collaborator.

**Comment by akturner** [comment]
@thanks!
