### ISSUE TITLE
Standardized file formats

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#12]
The file formats used within the analysis framework should adhere to some well defined standards. For example, they should be in formats easily accessible by users of the analysis framework (e.g. netCDF, ascii, or similar).
An additional consideration is that any example datasets intended to allow one to play with the analysis framework need to be small in file size (e.g. < 1GB of total example data sets).

**Comment by milenaveneziani** [comment]
Do we need this as an issue at this point? We *are* using standardized file format, so it doesn't seem like there is anything to fix to justify this issue open.

**Comment by pwolfram** [comment]
I think we are ok here.  Note that we really haven't resolved the example datasets issue but do have that tagged in other issues.  I'm closing for now...
