### ISSUE TITLE
seaice_timeseries.replicate_cycles is producing a plot that is too long

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#122]
My recent changes to `replicate_cycles` in #111 is producing some strange results.  The time variable of `dsShift` should be clipped to be as close as possible to the same as that of `ds`.

**Comment by xylar** [comment]
GitHub won't let me upload a picture right now.  I'll try again later...

**Comment by milenaveneziani** [comment]
do you understand why we didn't see this in our tests?

**Comment by xylar** [comment]
![iceareacell](https://cloud.githubusercontent.com/assets/4179064/23437836/ea0dfc4c-fe0f-11e6-9142-4a00adecffa4.png)

**Comment by xylar** [comment]
There's the picture.

> do you understand why we didn't see this in our tests?

Hmm, I guess I must have just been careless because this plot is right out of my output from #111.  Sorry about that.  But it should be quite easy to fix.

**Comment by milenaveneziani** [comment]
well, I did not get that in my test. I wonder if it has to do with the adjustment you made when I said that I was seeing one less cycle. Mine looked good after you made the change, but for some reason  this one does not.

**Comment by xylar** [comment]
Right, I think that's exactly what happened.  But it makes sense to have as much as 1 cycle too many like here and then just crop off the last bit to best match the end time of the `ds`.  I think that will be an easy fix when I get around to it.

**Comment by milenaveneziani** [comment]
agreed.

**Comment by milenaveneziani** [comment]
Addressed by #132.
