### ISSUE TITLE
Monthly files with more than one time entry die with unhelpful error

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Analysis#126]
If the Monthly time-averaged files have more than one time entry, MPAS-Analysis dies with:
```
ValueError: invalid literal for int() with base 10: ''
```
because it tries to parse the string '' into integer date and time values.  Right now, MPAS-Analysis is expecting one time field per file, so it would be helpful to check that and write a helpful error message.  This issue is a clarification of #125

**Comment by mark-petersen** [comment]
In the forward model, if you set MPAS-O flag to
```
 config_am_timeseriesstatsmonthly_write_on_startup = .true.
```
The result is that, on every restart, the first `mpaso.hist.am.timeSeriesStatsMonthly.*.nc` file has one entry of 45 minute duration, and a second for the rest of the month.  I think this is because of the coupling lag.  That first entry should not be used, so this is a configuration error.

One solution is for MPAS-Analysis to check if there are two entries in a Monthly file.  If so, it could print a warning with the `xtime_StartMonthly` and `xtime_endMonthly` of both entries, because the first is most likely nonsense.

**Comment by xylar** [comment]
Thanks @mark-petersen.  I think this is a bug, since there should be no requirement in MPAS-Analysis (specifically `mpas_xarray`) that there be one time entry per file.

I don't believe I have access to anvil.  Would it be possible to put one of the `mpaso.hist.am.timeSeriesStatsMonthly.*.nc` files that caused the crash somewhere on LANL IC so I can use it do debug a solution?

**Comment by mark-petersen** [comment]
I copied it over to edison here.  Note that there are two sizes, indicating where the restarts took place.  I also copied over a restart, input and streams files.  If you run MPAS-Analysis from `develop` on years 1-3 you will get the error.
```
edison04> pwd
/scratch2/scratchdirs/mpeterse/acme_scratch/edison/jonbob/20170221.beta0.GMPAS-IAF.T62_oECv3.anvil
edison04> ls -lh mpaso.hist.am.timeSeriesStatsMonthly.000?-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 6.5G Mar  3 10:37 mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 3.3G Mar  3 10:50 mpaso.hist.am.timeSeriesStatsMonthly.0002-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 6.5G Mar  3 11:03 mpaso.hist.am.timeSeriesStatsMonthly.0003-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 3.3G Mar  3 11:14 mpaso.hist.am.timeSeriesStatsMonthly.0004-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 6.5G Mar  3 12:14 mpaso.hist.am.timeSeriesStatsMonthly.0005-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 6.5G Mar  3 12:38 mpaso.hist.am.timeSeriesStatsMonthly.0006-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 6.5G Mar  3 12:57 mpaso.hist.am.timeSeriesStatsMonthly.0007-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 3.3G Mar  3 13:11 mpaso.hist.am.timeSeriesStatsMonthly.0008-01-01.nc
-rw-r--r-- 1 mpeterse mpeterse 3.3G Mar  3 13:28 mpaso.hist.am.timeSeriesStatsMonthly.0009-01-01.nc
```

**Comment by xylar** [comment]
@mark-petersen, thanks, that's great.  I'll give it a look as soon as I can.

**Comment by milenaveneziani** [comment]
@mark-petersen: I have talked about this briefly with @pwolfram and @xylar, and I was of the idea that this is really a bug in the way that ACME files were generated. After all, we expect to have one single time step in single monthly files: it seems to me that adding too many error checks will soon make the scripts too cumbersome.
My 2 c.

**Comment by vanroekel** [comment]
I agree with @milenaveneziani.  My preference is that  ``` config_am_timeseriesstatsmonthly_write_on_startup = .true. ``` be set to false by default as a PR to the main MPAS repo.  I find myself switching all the write_on_startup flags to false in practice anyway.

**Comment by mark-petersen** [comment]
I agree with that, and I am planning to make a PR today to change that configuration flag.  Still, I hate to have an unsuspecting MPAS-Analysis user get a meaningless error that causes frustration.  Perhaps we should check that a date string contains more than one character before we try to parse it into integer pieces.  If the date string is '' then we could error out on a message like
```
Error: Date string contains no characters and cannot be parsed.  This is sometimes caused by files with multiple time levels, when one is expected.
```

**Comment by xylar** [comment]
@milenaveneziani and @vanroekel, regardless of that fix, there's a problem with `mpas_xarray` assuming that there is one time entry per file.  This may be appropriate for the very specific case of monthly output in monthly files from ACME but is not appropriate for other runs, where someone could very well wish to store monthly output in yearly files (or any other conceivable combination of output interval and file interval).  So I think this issue still needs to be addressed.

I believe the analysis would still break or at least perform badly if there are multiple files per month, but it should not have broken where it did.  This indicates a bug.

**Comment by xylar** [comment]
I think this issue will eventually fall off the radar when we stop dealing with multi-file xarray data sets.  If it comes up again we can re-open.
