### ISSUE TITLE
Break analysis tasks into smaller subtasks

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#133]
Once parallel tasks have been merged #129, it will make sense to divide various analysis tasks into smaller subtasks that can (optionally) be run in parallel.  These would include:
  1. separating concentration and thickness analysis in `seaice_modelvsobs`, similarly to how `ocean_modelvsobs` handles SST, SSS and MLD.
  2. optionally, running `modelvsobs` tasks separately for different seasonal climatologies ('ANN', 'JFM', etc.)

This would likely require a new function for each task that enumerates (based on the config file) what the subtasks are.  Then, `run_analysis.py` would loop through the subtasks in the same way it loops through tasks in #129.

**Comment by xylar** [comment]
On further thought, Option 2 above might not actually save much time if most of the time goes into computing the monthly climatologies rather than computing seasonal climatologies from monthly climatologies and plotting them.  This should be tested before too much work goes into supporting more generalized subtasks.

**Comment by xylar** [comment]
Having separate MOC regions as separate tasks *might* also make sense.

**Comment by milenaveneziani** [comment]
@xylar: do you feel like this is not addressed by #282?

**Comment by xylar** [comment]
Yes, indeed!  Addressed by #282.
