### ISSUE TITLE
Missing xticks in timeseries plots

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#136]
All xticks are missing in the newer timeseries plots. It does not seem like something we changed recently, so I am not sure why we are seeing this now.
Here is an example from the latest ACME coupled beta1 run:

![iceareacellnh_20170302 beta1 a_wcycl1850s ne30_oec_icg edison_b1850c5_ne30_v0 4](https://cloud.githubusercontent.com/assets/8237579/23867549/d9455e24-07e1-11e7-8c27-7e4b3426d994.png)

**Comment by xylar** [comment]
@milenaveneziani, when I changed the time variable used in xarray data sets, it was no longer possible to use `pandas` directly to plot time series.  I updated the way the time axis was computed.  I assume this is behaving strangely in specific circumstances that my tests didn't expose.

The relevant line is likely somewhere near this one:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/shared/plot/plotting.py#L72

**Comment by xylar** [comment]
@milenaveneziani, this issue would be easier to address if you could point me to the config file that produced this output.

**Comment by xylar** [comment]
Was this produced with MPAS-Analysis on its own or as part of ACME diagnostics?  I guess what I'm really asking is, is this from develop or from master?

**Comment by milenaveneziani** [comment]
This is from develop.
The config file I used is this, on edison:
`~milena/MPAS-git-repositories/MPAS-Analysis-fortesting/config.20170302.beta1.A_WCYCL1850S.ne30_oEC_ICG.edison`

**Comment by xylar** [comment]
Thanks @milenaveneziani.  Could you update the permissions so I can read that file?

**Comment by milenaveneziani** [comment]
I did a test commeting out the line with `fig.autofmt_xdate()` and the ticks came back (yearly major ticks and monthly minor ticks, as it should be).
And permissions should be fixed now.

**Comment by xylar** [comment]
Okay, I would say removing `fig.autofmt_xdate()` isn't a great fix to the problem but it's a helpful step forward.  My guess is that it decided to get rid of ticks entirely when dates started overlapping, rather than getting rid of *some* dates, which is what it should do.  Anyway, maybe we can do some more thorough testing with time series of different lengths and figure out what works best.

**Comment by milenaveneziani** [comment]
@xylar: I did some testing while doing other things, and it seems that setting an angle for the ticklabels solves the issue. So, with `fig.autofmt_xdate(rotation=30)`, I get the following:

![iceareacellnh_20170302 beta1 a_wcycl1850s ne30_oec_icg edison_b1850c5_ne30_v0 4](https://cloud.githubusercontent.com/assets/8237579/23872109/a2204038-07f2-11e7-9ed6-9b24a3b1bf9f.png)

**Comment by xylar** [comment]
@milenaveneziani, I don't think that's why this works.  I think it works fine with a shorter time series but as soon as you have a long time series and the dates start to overlap, it doesn't get rid of *some* of them as you would expect, it gets rid of the entire tick axis.

I'm playing around with some other solutions.  I'll keep you posted.

**Comment by xylar** [comment]
@milenaveneziani, reading more on `plot_date`, I realize something I should have already realized: it assumes a Gregorian calendar, not the MPAS calendar.  We may have to do the tick marks ourselves rather than using plot_date.

This suggests that a proper solution to the date ticks may require me to invest a little time in this issue when I can.

**Comment by milenaveneziani** [comment]
oh great..
Glad that you found this. Since this will likely, and understandably, be a very low priority for you, should we look into a temporary solution? I could try a longer time series with the rotation on, for example.

**Comment by xylar** [comment]
Eh, it *should* be a low priority for me but the reality is that I'm working on it right now and I'll try to make it a higher priority ;-)

**Comment by xylar** [comment]
@milenaveneziani, okay, I have a solution.  It needs some cleaning up, which I will do tomorrow.

For now, how do you want the dates to be formatted at the bottom.  See this example:

![sst](https://cloud.githubusercontent.com/assets/4179064/23878289/d14a7924-0846-11e7-872f-7d02a0dcbc12.png)

I could do basically anything you want.  I think it used to be something like Jan-0001 but I don't recall for sure.

**Comment by xylar** [comment]
An updated figure with the format from before:
![sst](https://cloud.githubusercontent.com/assets/4179064/23878582/7bf3a4d0-0848-11e7-9e1d-f06bc8c5a98a.png)

**Comment by milenaveneziani** [comment]
that's great @xylar. Thanks.
The first option seems cleaner, don't you think?

**Comment by xylar** [comment]
@milenaveneziani, given that I have to handle them differently anyway, I'm thinking of including the month in the ticks only if they don't occur only at year bounds.  So when the time axis is short, several months from the same year might be included in which case the month would be included. But for longer time axes where only year boundaries are shown, there is no need to include the month.

**Comment by xylar** [comment]
Here are 2 examples showing the behavior:

![sst](https://cloud.githubusercontent.com/assets/4179064/23890201/fd49cdf0-0890-11e7-941c-bca9ebb65414.png)
![sst](https://cloud.githubusercontent.com/assets/4179064/23890218/0b36b00e-0891-11e7-92f4-de03715ceef7.png)

**Comment by pwolfram** [comment]
Can we close this issue now?

**Comment by xylar** [comment]
Fixed in #137

**Comment by milenaveneziani** [comment]
yep

**Comment by pwolfram** [comment]
Thanks!
