### ISSUE TITLE
Fully run-time configurable analysis capabilities

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#14]
A user of the analysis framework should not be required to edit python code to perform the analysis they are looking for. Additionally, to the extent possible, analysis should be configurable via some external capability (i.e. editing plot labels, or color bars?).  There should only one user-editable configuration file.

A simple mechanism should exist (e.g. modification of a small number of config options or specification of a small number of command-line arguments) by which a user can either run the full analysis suite or select and run a single analysis tool.  This requirement seeks to avoid the user having to “switch off” each analysis tool that the she does not want to use (as is currently the state in the ACME analysis repository).

**Comment by milenaveneziani** [comment]
Aren't we already fulfilling this requirement?

**Comment by xylar** [comment]
@milenaveneziani, I don't think so.  I find it frustrating that I have to set `generate = 0` for a bunch of analysis if I only want to run sea ice time-series analysis.  Until it's possible to say something like:
```
python run_analysis.py config.beta0 --only seaice_timeseries
```
or 
```
python run_analysis.py config.beta0 --not mbl_modelvsobs,sst_modelvsobs
```
or something similar, I don't think we're quite there yet.

**Comment by milenaveneziani** [comment]
ok, sounds good.

**Comment by pwolfram** [comment]
I'm closing because @xylar's recent PRs have resolved this issue unless I'm mistaken.
