### ISSUE TITLE
Config file in wrong place?

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#140]
Shouldn't this file be in the edison folder?

https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/configs/lanl/config.20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison

I can fix this if this is the case...

**Comment by pwolfram** [comment]
cc @milenaveneziani, am I missing something in particular here?  I think I should move this file to the configs/edison folder, right?

**Comment by xylar** [comment]
Nope, it's the config file for analyzing an Edison run that has been copied over the LANL.  The folders are those on LANL IC.  The file name is the official name of the run, including the machine it was run on (not the one where it is being analyzed).

**Comment by pwolfram** [comment]
Awesome, thanks for clarifying!
