### ISSUE TITLE
Support ACME short-term archiving

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#143]
When ACME short-term archiving will be turned on, the history files will be stored in component-specific archive directories. In particular, if `$rundir` is the root run directory, the files we will need for MPAS-Analysis to work will be archived in the following subdirectories:
1) `$rundir/ocn/hist` will contain *all* mpaso.hist files
2) `$rundir/ice/hist` will contain *all* mpascice.hist files (perhaps we should suggest this to be changed to `$rundir/sea-ice/hist`?)
3) the restart, namelists and streams files should remain in the `$rundir/run` directory, as is currently.

Therefore, we will need to make sure that, when short-term archiving is activated, the ocean and ice directories point to the right place.

Note that, in the `ACMEPreAndPostProcessing` csh scripts, we currently have a user-defined flag for short-term archiving.

**Comment by xylar** [comment]
@milenaveneziani, I think the solution is fairly simple here.  Under `[input]`, we need change `baseDirectory` to be one directory down from where it is in all the example config files and we need to add something like`runSubdirectory`, `oceanHistorySubdirectory` and `seaIceHistoryDirectory`.  I'm not attached to these names.  Then, we probably want to have them all default to `run` but in `ACME/PreAndPostProcessingScripts`, we would change them (if short-term archiving is on) to point to these directories.

We could even have the scripts fall back on the `runSubdirectory` if they don't find what they need in `oceanHistorySubdirectory` (etc.) or even have them just search in both always.

**Comment by milenaveneziani** [comment]
yes, I agree something simple should work. I will try to implement this option within the next submodule update.

**Comment by xylar** [comment]
I should note that #128 would make this quite a bit simpler because it puts quite a bit of common code in the base class that all analysis tasks derive from.  The `setup_and_check` method would be the place where these changes would go:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/128/files#diff-f4c01dd9c50e825c99d4d138d9001e07R62

If we make this change before merging #128, there will be quite a bit of redundant work that will have to be undone in #128.  That's fine if the change is needed before we can get around to merging #128.

**Comment by xylar** [comment]
@milenaveneziani, I'm working on this one today.

**Comment by milenaveneziani** [comment]
Thanks @xylar, and sorry if I didn't reply to this before.
So, I am not sure if the short-term archiving capability will be available in the next couple of weeks or not.. I could ask around.

**Comment by xylar** [comment]
Addressed by #153
