### ISSUE TITLE
MOC analysis corrupts mask file on anvil

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#145]
After each time I run the MOC analysis on anvil for an EC6030v3 test the mask file becomes corrupted.  For example, I can successfully run the analysis and then if I run again (changing nothing), I get the following error 
```
  Reading region and transect mask for Atlantic...
Traceback (most recent call last):
  File "./run_analysis.py", line 259, in <module>
    analysis(config)
  File "./run_analysis.py", line 196, in analysis
    variableMap=oceanVariableMap)
  File "/blues/gpfs/home/lvanroe/MPAS-Analysis/mpas_analysis/ocean/meridional_overturning_circulation.py", line 139, in moc_streamfunction
    dictClimo, dictTseries)
  File "/blues/gpfs/home/lvanroe/MPAS-Analysis/mpas_analysis/ocean/meridional_overturning_circulation.py", line 228, in _compute_moc_postprocess
    ncFileRegional = netCDF4.Dataset(regionMaskFiles, mode='r')
  File "netCDF4/_netCDF4.pyx", line 1811, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12626)
IOError: NetCDF: Unknown file format
```

If I copy a fresh file into the location of the corrupted file, the analysis works fine again.

Has this been seen elsewhere?  My directory is 
```
/home/lvanroe/MPAS-Analysis
```
and I am using config.default right now.

**Comment by milenaveneziani** [comment]
Interesting, thanks for reporting this. We haven't had this happening on edison and lanl, where we tested the MOC script. 
And if you have the script print the corrupted filename, and then you try to ncdump it from your prompt, what kind of error message do you get?

**Comment by vanroekel** [comment]
Odd, when I do an ncdump, it says file does not exist.  The file size is 0 bytes.

**Comment by xylar** [comment]
That's weird! Could you check if the analysis doesn't think the file exists? Even if so, I don't understand why it wouldn't simply be overwritten successful (which we definitely don't want to do!)

**Comment by milenaveneziani** [comment]
The file is not created within the MOC script, it is simply read in. This would be a file that you had to move to a directory on anvil, right @vanroekel?

**Comment by xylar** [comment]
Ah, a mask file, not a mapping file.Ignore what I said.

**Comment by vanroekel** [comment]
Yes correct, it is Mark's EC6030v3 region mask file.  when I do ncdump -h on it, I get "file does not exist"  It is very weird.

**Comment by milenaveneziani** [comment]
And you can 'ls' it? Is it possible this has to do with netcdf versions?

**Comment by vanroekel** [comment]
Yes, ls -l yields
```
-rw-r--r-- 1 lvanroe collab 0 Mar 20 12:30 ../EC60to30v3_SingleRegionAtlanticWTransportTransects_masks.nc
```

Note that the size is zero.

**Comment by milenaveneziani** [comment]
could you copy it again and see if you can reproduce this issue?

**Comment by vanroekel** [comment]
I have reproduced this error multiple times on anvil.

**Comment by milenaveneziani** [comment]
that's really weird. The analysis only reads from it.. And you don't have the same problem for other files, like mocTimeseries and moc climatologies?

**Comment by milenaveneziani** [comment]
I guess you never get to that part..

**Comment by xylar** [comment]
@vanroekel, could you add artificial breaks (e.g. just put in `exit()` in various places) in the code to figure out where the file gets corrupted?  Is it somehow getting mangled by line 228, even though mode is *clearly* read?

**Comment by vanroekel** [comment]
@xylar and @milenaveneziani problem solved.  The system default netcdf library was being loaded and conflicted with the python dataset/netcdf4 module.  This seems like an environment issue and not MPAS-Analysis, so I will close this issue

**Comment by milenaveneziani** [comment]
This is something good to know though, so that we can give specific instructions to the user. @vanroekel: could you please summarize briefly what you had to do to set the system right?
We can update the README while taking care of #144

**Comment by xylar** [comment]
@milenaveneziani, this sounds too specific to Anvil to put in the README.md.  Presumably it's a matter of unloading specific netcdf4 modules.

**Comment by milenaveneziani** [comment]
Isn't it possible though that we might have the same problem somewhere else; we just didn't run into it because of how our own environments are setup?

**Comment by xylar** [comment]
Hmm, well I guess we could add something to the readme if it would affect a substantial number of users of MPAS-Analysis.  But for now I think it sounds very specific to one machine.  I have run into problems with conflicting NetCDF libraries on NERSC machines.  But these issues really have very little to do with MPAS-Analysis and more to do with how you use NetCDF on HPC machines.  I guess I just don't want to confuse or over complicate the README file with problems that aren't clearly related to this project.
