### ISSUE TITLE
Add support for regions other than Atlantic in streamfunctionMOC

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#156]
Currently, we only support the `Atlantic_MOC` region but we need to add support for the 4 other MOC regions defined by `geometric_features`.  This will involve reading the region names directly from the mask file (rather than hard-coding indices).

This is also a chance to do some optimization to try to make the MOC computation a bit faster and maybe also less memory intensive.

Ideally, we also need a process for automatically generating the masks and transects we need, given a mesh file.  Since the tools for doing this are still proprietary (in `MPAS-Tools`), this will need to be done outside of MPAS-Analysis, at least for now.

**Comment by milenaveneziani** [comment]
A heads-up that we may want to support the MOC (postprocessed and AM) for the IndoPacificMOC region only (besides the Atlantic) because of the open channels between the Indian and the Pacific MOC basins.

**Comment by xylar** [comment]
Okay, good to know.  I think the easiest way to handle this would just be to have a list of regions to compute MOC on.  There is also the global 65S to 65N region.  Is that one we will actually use?  Or does global really mean global?

**Comment by milenaveneziani** [comment]
The global 65S-65N is for a OHC comparison with obs, when we get through processing that data set.. It makes more sense for present-day or transient climate simulations though.
We mostly want AtlanticMOC and IndoPacificMOC for the MOC and MHT calculation. And we need southern transects for these only.
The other, 'regular' ocean basin regions (including the Nino regions) are for these AM's instead: `surfaceAverages`, `layerWeightedAverages`, and `waterMassCensus`.
