### ISSUE TITLE
Support platforms typically used for ACME

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#16]
Analysis framework must work on all platforms where conda works.

**Comment by pwolfram** [comment]
Note, we have no plans to support Windows, only Unix-based OSes.

**Comment by xylar** [comment]
@pwolfram, is there any reason to think we don't already satisfy this requirement?

**Comment by milenaveneziani** [comment]
We have tested things on the LLNL machine Aims, so we are good there.
We haven't tested at ALCF, but the python conda package was installed.
I'd say we can close this.

**Comment by pwolfram** [comment]
Agreed
