### ISSUE TITLE
Mechanism to access data sets for comparison

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#17]
Many analysis tools will use datasets (e.g. observations or model results) for comparison with MPAS results.  A mechanism should exist for downloading these datasets automatically from data archives (public or private).  When possible (i.e. when these datasets are publicly available in the required format), the analysis should acquire these datasets from public sources to ensure the analysis can be used by the broadest possible community.  

Observational data should be observational datasets, potentially stored in a separate repository (to keep analysis script repositories light-weight).  For example, we could keep them in a centralized location where data that is need is downloaded and cached locally.  
- [ ] Keep track of hash sum verification that files are the same.  
- [ ] Want this resource to be publicly available (could be https://git-lfs.github.com/ or http://data.kitware.com/ or something else).
- [ ] Only pull in necessary data / provide soft links to data as possible.

**Comment by pwolfram** [comment]
@milenaveneziani, at present we are simply using a cached location for the observational datasets.  What are your ideas on how we should handle this issue?  In the past we have discussed keeping the observational datasets on a cloud-based data server and then accessing them from the analysis framework.  Do we need to move forward on this goal?  If so we may want it on our roadmap.

cc @xylar, @vanroekel

**Comment by milenaveneziani** [comment]
Yes, I agree we should have it on our roadmap. We should be better organized on both the MPAS standalone side and the ACME side (moving observations to the ACME repo, to start with..).

**Comment by xylar** [comment]
Part of this has been addressed by #375 

I'm going to close this and add the unaddressed items as (lower priority) issues
