### ISSUE TITLE
Consider getting rid of Author and Last Modified in docstrings

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#176]
I would like to get rid of the `Author` and `Last Modified` sections of docstrings:
  1. I find it tedious to keep them updated, and they often get forgotten.
  2. This information can be obtained relatively easily by bringing up the file on GitHub and looking at "blame" (which gives this information not just for each function but each line).
  3. Sphinx (more specifically numpydoc) doesn't recognize these categories and either ignores them with a warning or (in the case of module docstrings) includes them in the documentation.  This is distracting when you are looking for actual problems when generating documentation and, when it shows up in the docs, is irrelevant to the user.

**Comment by xylar** [comment]
@pwolfram, @milenaveneziani and @vanroekel, I'd be keen to hear any reasons you have for keeping these.

**Comment by vanroekel** [comment]
@xylar no objections from me.  I certainly agree with your point 1 above.

**Comment by pwolfram** [comment]
We have the problem though that if code is removed from a function that won't show up in git blame.  

Is there a way we can comment them out with respect to Sphinx?  I think we need them for development but it would be good if we could eliminate them from the Sphinx parsing.

**Comment by xylar** [comment]
@pwolfram, you find these useful?

**Comment by xylar** [comment]
I don't find them useful (ever) for development and I think there's a good reason they aren't used in other development workflows that I've seen.  They're a big pain to remember to update.

I'm sure there could be a workaround for Sphinx or we could just live with them being part of the documentation and/or warnings from sphinx.

**Comment by xylar** [comment]
I agree that `blame` won't show if a file/function has been changed by pure deletes.  But the commit history of the file certainly would show the date of the last commit that affected the file.  It seems hard for me to imagine a case where you would like to quickly know who had deleted lines from a given function most recently and you couldn't find it quickly from the commit history.  Would such a case really be worth all the trouble of keeping author names and last modified around?

**Comment by philipwjones** [comment]
I like having the author documented in code preambles - as the equivalent of a publication. The author gets credit for the contribution in a prominent way. Having said that, it doesn't need to be part of any self-generating documentation. Just good to have in the code somewhere at the top.

**Comment by xylar** [comment]
@philipwjones, I could see that being useful.  We could have the authors in the docstring of each python file without including it in each function.  That would both be substantially less work (therefore easier to keep up with) and wouldn't show up in the documentation, since the module docstrings aren't used in sphinx to my knowledge.

Do you have any opinion about the usefulness (or lack thereof) of noting the date a function and/or module was last modified?

**Comment by philipwjones** [comment]
For modifications,  we might want to document for major re-writes, but otherwise...It's occasionally useful, but as mentioned can be retrieved using other methods. Subversion had a way to automate it by adding a keyword that got replaced on commit with the date. As others have mentioned, unless it's automated, it won't be accurate anyway and is more likely to be misleading.

**Comment by pwolfram** [comment]
This all makes sense-- maybe we should keep authorship and drop the date then?  I'd like to keep authorship at a function level, I would say that we could drop the module-level authorship if anything because it is really too coarse to be useful.

Regarding deleted lines-- I had an issue with MPAS I essentially had to do find out where the deleted lines were to figure out why the code wasn't working-- it is much easier knowing who is responsible for the design than resorting to git tricks.

**Comment by xylar** [comment]
Anyone else have an opinion either way about authorship at the function vs. module level?  I really feel like `blame` is a much better tool for what you're talking about @pwolfram.  You can always use blame referring to commits in reverse order (a trick I turned up earlier with a quick google search) to check for deleted lines -- they show up as inserted lines in reversed `git blame` calls.

But I guess since you feel strongly about it I will support sticking with authorship at the function level.

**Comment by pwolfram** [comment]
Do you mind sharing the link @xylar?  If there is an easy way to get this information I would change my mind and support removal of authorship at function level.

**Comment by xylar** [comment]
@pwolfram, I was looking at: http://stackoverflow.com/questions/4404444/how-do-i-git-blame-a-deleted-line

Looking it over again, there seem to be cases where it wouldn't work (e.g. lines deleted before a merge commit).

**Comment by xylar** [comment]
@milenaveneziani, any opinion?

**Comment by milenaveneziani** [comment]
sorry for not chipping in, but no, no particular opinion on this one.

**Comment by xylar** [comment]
I'm closing this with the understanding that we will phase out `Last Modified` because it has the tendency to be inaccurate but that we will keep `Authors` per function/method.

Regarding sphinx/numpydoc, I think we can live with the warnings generated by the unknown `Authors` section when autogenerating documentation from docstrings.
