### ISSUE TITLE
Robust exception handling

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#18]
The analysis framework should be fault-tolerant to a variety of error situations. For example, when a data set or input file is missing, or an analysis is misconfigured. Individual processes should be allowed to "error out" without halting the system.

**Comment by milenaveneziani** [comment]
This issue is similar to the modularity thing: it is going to be on-going as the analysis evolves. I would suggest to close it, and we will have specific issues about this in the (very) near future.

**Comment by pwolfram** [comment]
Sounds good @milenaveneziani, we have an issue #58 to help address this and are on the lookout to do better exception handling so I'm going to close this for now.  Please reopen if needed.
