### ISSUE TITLE
Nino34 time series not being cached

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#186]
All other time series are cached from run to run.  I somehow missed Nino34.

**Comment by milenaveneziani** [comment]
Maybe we can add this in v0.3?

**Comment by xylar** [comment]
Yes, absolutely.  I just wanted to make a note of it so I don't forget.

**Comment by xylar** [comment]
This should happen as part of the switch to `ncrcat`.

**Comment by xylar** [comment]
Should be addressed by #271

**Comment by milenaveneziani** [comment]
and this as well?
