### ISSUE TITLE
Compare different model results

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#212]
A requested capability would be to compare these same fields between different model runs in addition to comparing to observations. The current plot structure is show model, show obs, show difference. The added functionality would be show model 1, show model 2, show difference.

**Comment by stephenprice** [comment]
Thanks @xylar -- sorry I was out of town as of noon-ish on Friday so didn't get a chance to return to this until now.

**Comment by xylar** [comment]
#292 is intended to address this issue.
