### ISSUE TITLE
Add analysis of sea ice formation and melt rates

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#216]
Assuming rates of sea ice formation and melting are available in the timeSeriesStats AM, an analysis task that compares these against SOSE and possibly satellite-derived formation rates (e.g. Tamura 2008) would be useful.

**Comment by xylar** [comment]
I added the "sub-ice-shelf" tag because this analysis would be of interest to the ALCC project related to ice-shelf melting.

**Comment by akturner** [comment]
Hi, I have a prototype script that can calculate a mass balance for a region, so this would be useful for this.

**Comment by xylar** [comment]
Excellent!  Please do share and I can see if I can bang it into MPAS-Analysis form.  This worked well for @JeremyFyke's script for ocean transects.

Are you aware of any observations to use?  If not, I'll see what we might be able to use from SOSE.  Or the Tamura et al. [citation needed] production maps might be another option.
