### ISSUE TITLE
Ability to purge old analysis results

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#22]
All products of the analysis framework must be easily removed to ensure there is no mix of new and old analysis products, or products representing multiple model runs.

**Comment by xylar** [comment]
This is presumably going to require each analysis to have a `purge` function that is aware of which files it generates.  When we implement this, we might as well also add a `check` function that can be used to make sure the required input files are available (observations, current model data and reference model data).

**Comment by pwolfram** [comment]
This should be addressable via an approach like in #127, e.g., we should consider defining a `purge` method for the class that will facilitate this functionality.

**Comment by xylar** [comment]
Hopefully addressed by #260
