### ISSUE TITLE
MHT is computed from timeSeriesStatsMonthly stream, not meridionalHeatTransport stream

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#221]
I believe that the MHT is being computed using `timeSeriesStatsMonthly`, whereas the intention seems to have been to use the `meridionalHeatTransport` stream.

On this line:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/ocean/meridional_heat_transport.py#L87
the list of input files is taken from the `timeSteriesStatsMonthly` stream (named just `timeSeriesStats` in MPAS-Analysis).  Later on, on this line:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/ocean/meridional_heat_transport.py#L141
there is a check to ensure that at least one file exists in the `meridionalHeatTransport` stream.  Yet, this stream is not actually used in the analysis task.

I believe this is a mistake, though the fields needed to compute the MHT seem to exist in both streams at the moment.

This bug is important because currently `ncclimo` assumes that climatologies are always computed from the `timeSteriesStatsMonthly`.  If we need this not to be not the case (and I think we do), it would be important to get more flexibility built into `ncclimo` to handle other streams.

**Comment by xylar** [comment]
@mark-petersen, can you verify that this is a bug?  If so, I'm happy to fix it (it's a one-line change).

**Comment by milenaveneziani** [comment]
Hi @xylar: no, this is not a bug. We intend to use monthly means of the MHT computed fields, ie output of the meridionalHeatTransport AM that went through the timeSeriesStatsMonthly AM. Similarly to what we do for OHC (layerWeigthedAvg AM) and SST trends (surfaceAvg AM).

**Comment by xylar** [comment]
@milenaveneziani, then why is there a `meridionalHeatTransportOutput` stream, and why do we have a check in the analysis task to make sure at least one file from the `meridionalHeatTransportOutput` stream exists, even though we never use any files from this stream?  That, at least, seems like a bug to me.

**Comment by milenaveneziani** [comment]
I think we have an instantaneous (history file) stream for each AM, not only for MHT. But you are right, we do not really need to check for the meridionalHeatTransportOutput stream, just that the config_am_meridionalHeatTransport option is turned on and that we have timeSeriesStats on. Can you confirm this @mark-petersen?

**Comment by xylar** [comment]
Okay, so looking at this in more detail, it seems that the `meridionalHeatTransportOutput` stream is used to read in `binBoundaryMerHeatTrans`, `refZMid` and `refBottomDepth`.  So we do, indeed, need the first file from this stream.

I'll close this issue.
