### ISSUE TITLE
remove variable, namelist and streams maps

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#223]
For backwards compatibility, we have used maps between variable names in MPAS-Analysis and their counterparts in various MPAS/ACME versions.  This has been useful as variable  names in the `timeSeriesStats` AM (and stream names and namelist options) were changing fast and as different components had different naming conventions within the same ACME version.  The situation seems to have "stabilized" to the point where it the extra confusion introduced by the variable name mapping is probably not worth the complexity.  I suggest we remove these capabilities.

The other issue with attempting to maintain backwards compatibility is that we can really only be sure we are backwards compatible if we continue to test MPAS-Analysis on several earlier versions of ACME/MPAS, which is a logistical challenge, particularly as old simulation results are archived and no longer available for testing.

Instead, a system is needed where tags on MPAS-Analysis indicate which ACME and MPAS component major version tag(s) they are compatible with.  A-Prime will presumably need to do the same.

**Comment by milenaveneziani** [comment]
@xylar, this was solved by #241, right?

**Comment by xylar** [comment]
Yes, indeed!
