### ISSUE TITLE
Consider reformatting OHC plot

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#229]
In this example, I find the legend much more useful than the description in the plot title used in current OHC plots (see example below).  The axis labels and plot colors are perhaps also preferable.  

![image](https://user-images.githubusercontent.com/4179064/29915196-54f6b038-8e3b-11e7-940e-9e3d104e508a.png)

Note: support for comparisons like this between multiple models is also needed, see #212.

A current OHC plot:
![ohc_global_20170313 beta1 a_wcycl1850s ne30_oecv3_icg edison](https://user-images.githubusercontent.com/4179064/29915317-c96d61f0-8e3b-11e7-8c16-8f13c6ec73a1.png)

**Comment by xylar** [comment]
This would appear to be the starting point:
https://github.com/MPAS-Dev/MPAS-QuickViz/blob/master/ocean/global_ohc_sst/OHC_SST_calculations.ipynb

**Comment by milenaveneziani** [comment]
Addressed by #261.
