### ISSUE TITLE
Provenance stored in user-viewable output files

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#23]
The analysis framework is required to be reproducible, and fully descriptive. To this end, a mechanism is required for documenting as much as possible about a given run through the analysis framework. This could include information such as the git version of the analysis framework, information about all of the input files, commands run, etc.  The analysis framework should provenance all the data sources (including model hashes and configurations as well as observational data sources) and operations performed on this data that are needed to fully reproduce the produced analysis, independent of machine and user.  Ultimately, analysis package operations could be documented in a history file that is used by the analysis package to fully replicate the analysis.

**Comment by xylar** [comment]
Partially addressed by #240

**Comment by xylar** [comment]
@pwolfram, would you be okay with me closing this issue?  We could open issues with more specific issues about provenance needs.  I have some very basic stuff (git hash, user, command line, etc.) in an xml file associated with each image.  This could be expanded but I don't feel like this issue will do much to prod us in that direction.

**Comment by pwolfram** [comment]
Thanks for checking into this @xylar-- agreed that #240 is a good minimal approach.
