### ISSUE TITLE
Add WOCE (particularly Drake Passage) PD plotting

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#230]
An analysis task is needed to plot potential density across the Drake Passage:

![image](https://user-images.githubusercontent.com/4179064/29915434-339fbbcc-8e3c-11e7-8d3b-c638194773be.png)

**Comment by xylar** [comment]
This script seems to work on the same principle (though not for the Drake Passage, at least in the example plots):
https://github.com/MPAS-Dev/MPAS-QuickViz/blob/master/ocean/section_plots/Zonal_meridional_Section_comparison.ipynb

**Comment by xylar** [comment]
#327 should be a big step to supporting a plot along the lines of this example.  One question is whether the contour plots like in the example figure are more useful than a series of panels like we are planning for other transect data.  Potentially this could be a flag in the config file.

**Comment by xylar** [comment]
@gstreletz, I believe this is essentially one of the items on your work plan, correct?  Not necessarily the drake passage but a plot of the type above.

**Comment by gstreletz** [comment]
@xylar, yes, that is correct.  I plan to add support for plotting comparison plots of this type.  Initially it will be for the WOCE and SOCE temperature and salinity data, as for #327, but it shouldn't be difficult to then adapt that for use with other data.

**Comment by gstreletz** [comment]
PR #450 (Transect contour plots) partially addresses this issue, providing the contour comparison plot type shown above.  To add Drake Passage PD plotting using the code from this PR, all that is needed is to create a GeoJSON file for the Drake Passage transect.

**Comment by xylar** [comment]
My thoughts on creating a Drake Passage task are:
* Make downloading the Drake Passage (and probably other ocean geojson files from `geometric_features`) part of the script for downloading observations
* Reorganize `config.default` and the example config files to just specify the `diagnostics` directory and not all of the unnecessary subdirectories and files (to better reflect the more rigid structure for observations, region masks and mapping files we now require and which the script for downloading observations enforces)
* Make a task that inherits from `GeojsonTransects` for the Drake Passage (and possibly other transects from `geometic_features`).  This task would know where to find its `geojson` file(s) based on the location of the `diagnostics` directory

**Comment by xylar** [comment]
I don't think we need a new geojson file after all.  We have the WOCE transect for the Drake Passage already.  All that we would need to do is compute potential density from the T and S from WOCE and compare that against the model (optionally as contour plots as above).
