### ISSUE TITLE
Add OHC 2-d map

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#233]
It would be interesting to add plots of OHC anomaly maps like these ones:

![middlelayer](https://user-images.githubusercontent.com/8237579/29932345-3fdcfd38-8e31-11e7-957a-ee15a1a30ac6.png)

**Comment by xylar** [comment]
Solution under review #342

**Comment by xylar** [comment]
Addressed by #342
