### ISSUE TITLE
Add mass-transport across transects plotting

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#242]
We ideally want to have an automated production of transect plots, e.g., 
![transportdrakepassage](https://user-images.githubusercontent.com/4295853/30297793-3c544dc8-9706-11e7-8307-cb160a3876f8.png)

A starting point is https://gist.github.com/pwolfram/33d1d26b64eebd255dd8c56ad18c44ed, but generalization and cleanup for MPAS-Analysis is needed.

**Comment by xylar** [comment]
@pwolfram, do you think it would make sense to plot the mean observed value as a line value as a line, too (like @stephenprice is doing here: https://github.com/MPAS-Dev/MPAS-Analysis/pull/237#discussion_r137891786 or like we use for MHT observations)?  I ask because this might help us to have a unified approach for making these kinds of plots with observations and error bars.  Something like here:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/shared/plot/plotting.py#L619

**Comment by pwolfram** [comment]
@xylar, great idea!  I had just made it a shaded region for simplicity and your idea of specifying the mean value too for the observation, as well as pursuing unified consistency, is much better.

**Comment by pwolfram** [comment]
I should also note that the general goal here is to produce visual output from the transect data we are already producing in MPAS-O; unification with all MPAS-* cores is optimal.

**Comment by xylar** [comment]
@pwolfram, taking a look at your example script, you provide a link to a transects mask file.  Would you foresee storing a pre-generated version of that file on each supported model grid (like we currently do for the MOC regions and we plan to do for ice-shelf regions)?  Or would you want the user to specify a path to the transects mask file in the config file?  Or both might also be possible.  I could imaging that it would be kind of a pain for most users to supply the file name if we required them to do so in the config file.

Maybe I'm getting too far into the weeds on this one already.  But it seems pretty easy to implement other than deciding this one issue.

**Comment by xylar** [comment]
Also, were you eager to implement this one or would you like me to give it a go?

**Comment by pwolfram** [comment]
Time is tight for me until end of fiscal year-- you are more than welcome to have a go before then but please don't feel obligated to do so because I can do this when I have more time too.

**Comment by xylar** [comment]
Okay, great!  I'll give it a go if I have time.  Otherwise, I'll leave it to you when you have time.

**Comment by milenaveneziani** [comment]
To add a bit on the transect mask files: we should have a workflow for generating those files that is similar to that for generating regional mask files. Start from a geojson feature and use one of the MPAS-Tools to generate a mask file given a certain grid. We haven't really used this workflow much yet, but it's there and it's probably time to get it finalized, also regarding the region mask files. I will probably add all this to the Confluence discussion page that I have created this morning.

**Comment by xylar** [comment]
@pwolfram and @milenaveneziani, I looked in geometric features and didn't see any ocean transects other than the ones for deepening critical channels.

Are there other transects on a branch somewhere that need to be merged?

If not, would be first step for adding this analysis be adding the transects themselves to geometric features and creating a script for extracting them on each of our supported meshes?

**Comment by pwolfram** [comment]
@xylar, I'm not sure.  @mark-petersen, do you recall how the transects were produced?  I have some recollection you or others from CCS oversaw their production but don't know for sure.

**Comment by mark-petersen** [comment]
Here is the original geojson file with the transects.
https://gist.github.com/mark-petersen/ea9ca550258c9a9d6d5009d62aae8deb
I originally created those points in the matlab file, here:
https://github.com/MPAS-Dev/MPAS-Tools/blob/master/visualization/transport_sections/transport_sections.m#L98
which was used for the transport calculation for the 2013 MPAS-Ocean paper.

@xylar I agree that those transects belong in geometric features.  Thank you for thinking of this. 
 We of course need group labels here, i.e. one group of transects is for channel deepening, and another is for measuring transport.

Here is how I made the transects for the transport calculation:
```
New mask file here:
/lustre/scratch3/turquoise/mpeterse/runs/c62n/ocean/global_ocean/EC_60to30km/spin_up/init_step2/EC60to30v3_transect_masks.nc

I obtained it with this command:
gr-fe2.lanl.gov> ls -lh MpasMaskCreator.x
lrwxrwxrwx 1 mpeterse mpeterse 117 Aug 23 14:25 MpasMaskCreator.x -> /turquoise/usr/projects/climate/mpeterse/repos/MPAS-Tools/MPAS-Tools/grid_gen/mesh_conversion_tools/MpasMaskCreator.x
gr-fe2.lanl.gov> ./MpasMaskCreator.x ocean.nc EC60to30v3_transect_masks.nc -f standard_channel_transects.geojson

This is the variable you want:
int transectEdgeGlobalIDs(nTransects, maxEdgesInTransect) ;
and
        int transectEdgeGlobalIDs(nTransects, maxEdgesInTransect) ;

Also the names:
gr-fe2.lanl.gov> ncdump -v transectNames EC60to30v3_transect_masks.nc|tail
  "Florida-Cuba, Caribbian                                        ",
  "Florida-Bahamas, Carib. 27 lat, -80  to -78.8lon,              ",
  "Indonesian Throughflow, -9  to -18 lat, 116E lon, section J89, ",
  "Agulhas                                                        ",
  "Mozambique Channel,    -25 lat,  35  to  44E lon, section I4 , ",
  "Bering Strait, Arctic                                          ",
  "Lancaster Sound, Arctic                                        ",
  "Fram Strait, Arctic                                           -",
  "Robeson Channel, Arctic                                       -" ;
}

for example:
ncdump -v transectEdgeGlobalIDs EC60to30v3_transect_masks.nc | less

 transectEdgeGlobalIDs =
  101529, 513657, 357783, 397758, 120490, 233193, 280547, 16928, 41137,
    456864, 291317, 261218, 361977, 135147, 337129, 416677, 62663, 700890,
    325973, 611324, 51838, 532568, 709828, 521163, 560779, 70448, 131462,
    475691, 121647, 380969, 161590, 28005, 634490, 378511, 469596, 711780,
    26967, 711151, 212307, 693835, 474385, 178355, 453234, 424455, 612346,
    194753, 261139, 545148, 449618, 650889, 516263, 103521, 235823, 162096,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
```

**Comment by xylar** [comment]
Great, that seems easy enough to add to `geometric_features`.  Scripting the process for producing the corresponding mask files fore each grid also seems like a straightforward extension of the process we have for the MOC masks.
