### ISSUE TITLE
Snapshots in horizontal and vertical

### ISSUE THREAD

**Issue by mark-petersen** [MPAS-Dev/MPAS-Analysis#244]
Our experience this summer shows how important it is to have a large variety of images in our standard visualization suite.  In particular, instantaneous snapshots are needed to probe overall simulation health, vertical and horizontal mixing parameters, and algorithms.  The difficulty is that a person could never look at all levels, time slices, variables, and regions.  Here I propose a standard set of history snapshots as a way to at least view some basic characterization of the simulation.

MPAS-Analysis should make plots of the following:
1. **Time**: When MPAS-Analysis (and eventually, A-Prime) is run, create plots at n year intervals, default to every 5 years.
2. **Variables**: temperature, salinity, divergence, verticalVelocityTop
3. **Horizontal levels**: At depths of 50m, 250m, 1000m, and bottom cell.
4. **Horizontal zoom**: One image ~12 cells wide to detect noise; one of a larger region (say, 10x10 degrees)
4. **Vertical profiles**: Show ~20 columns together as line plots.  Two separate plots of vertical extent: One 0 to 500m, another 0 to full depth.
5. **Regions**: Philippines, Western Equatorial Pacific region. Others?  Perhaps the North Atlantic or Southern Ocean?

**Comment by mark-petersen** [comment]
I'm open to feedback on this.  It will be a compromise between producing numerous plots and time required for MPAS-Analysis.  We have a full mock-up of this from our work this summer.  Results are here:
https://acme-climate.atlassian.net/wiki/spaces/OCNICE/pages/128949324/Simulation+Plan+June+21
and example notebook is here:
https://github.com/mark-petersen/testQuickViz/blob/master/ocean/horizVertStructure/HorizVertStructurePlusVertVel_c68k_4e12Del4.ipynb
Sorry, I haven't cleaned it up yet.  The slick python code is due to @pwolfram and @vanroekel.

**Comment by mark-petersen** [comment]
It would be nice to see the seasons.  On the time axis, we could make monthly plots, but only do it every five years.

**Comment by xylar** [comment]
I think it's clear that this is outside the scope of any current plans for MPAS-Analysis.  @mark-petersen, feel free to re-open this if you have a plan for who will add this and when.
