### ISSUE TITLE
Bias in sea ice thickness and perhaps concentration should be more extensive

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#256]
The bias in sea-ice thickness should cover all areas where either the model or the observations have non-zero thickness.  The same is likely true for concentration, though I'm not as sure about that one.

**Comment by xylar** [comment]
@akturner and @milenaveneziani, what do you think?

**Comment by milenaveneziani** [comment]
@xylar: is this the same issue raised in #250? And should be solved by #255?

**Comment by xylar** [comment]
@milenaveneziani, no this is another issue.  I could add a fix to #255 but it might be better to address it separately.

The problem is that the extent in MPAS-SeaIce and in the observations is different.  Right now, if a given cell on the comparison lat-lon grid is outside the sea-ice extent for *either* grid, we mask it out.  I think this is not the correct behavior.  Instead, we should mask out only those cells that are outisde the sea-ice extent on *both* grids.  Does that make sense?  If so, do you agree that the behavior should be changed as I suggest?

**Comment by xylar** [comment]
Hmm, I realize now that my suggestion is a little tricky to handle, since we still do want things to be masked out where MPAS-SeaIce thinks there's land but the observations don't.  I think there should be a way to handle this, though.  I have done something similar in my Antarctic analysis tasks.

**Comment by xylar** [comment]
I believe I was incorrect and the problem does not exist.  Here is an example of an ice-thickness comparison:
![image](https://user-images.githubusercontent.com/4179064/33069391-b42dcca8-ceb4-11e7-8bf0-532a5bad5672.png)
The bias plot does include regions that are zero (or close to it) on the left but non-zero in the middle.  The only regions being masked out are those that are presumably NaN on the left because they are "land".
