### ISSUE TITLE
OHC plot: plus can't be distinguished from thick line for long time series

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#286]
I ran the analysis on 100 years of data.  The OHC plot looks like this:
![ohcanomaly_global_b_low_res_ice_shelves_1696_jwolfe_layout_edison](https://user-images.githubusercontent.com/4179064/33783636-ddc0fd86-dc5d-11e7-8e40-5956bea19e16.png)
The trouble is that he plus signs all overlap to the point where they look like a line.  We should probably come up with a fix.

**Comment by milenaveneziani** [comment]
argh.
might be because the symbols are too big?

**Comment by milenaveneziani** [comment]
could you try changing the linewidth to something like 1.2 for the '+' case when you have a minute? (now it's set to 3).

**Comment by xylar** [comment]
@milenaveneziani, I'm not sure making the pluses smaller is really a solution.  With a long enough time series, that will just look like a thinner line.  Also, I think line width doesn't do anything to the pluses because that's controlled by `markerSize` or something similar.  But I could be wrong.

**Comment by xylar** [comment]
Leif's suggestion was to make the 4 depth categories different colors with the main run as solid and the reference run as dashed.  That would work with this plot but it would make the comparison with other figures difficult.  My suggestion would be to make the 3 sub-depths different shades of either red or gray, with the upper fraction somewhat lighter and the bottom fraction somewhat darker.  I will try this out and post an example of what I'm suggesting.

**Comment by xylar** [comment]
Hmm, my idea isn't too convincing...

![ohcanomaly_global_gmpas-qu240](https://user-images.githubusercontent.com/4179064/33788423-6de5e58e-dc72-11e7-906f-566cdfbf9f9c.png)

**Comment by xylar** [comment]
Okay, I think I have a plausible fix:
![ohcanomaly_global_b_low_res_ice_shelves_1696_jwolfe_layout_edison](https://user-images.githubusercontent.com/4179064/33789730-1380c20e-dc7b-11e7-8a23-4eb1cfb19105.png)
I have not allowed there to be more than around 300 pluses.  If we want to change that to a smaller number, that's fine.

**Comment by xylar** [comment]
@milenaveneziani, what do you think of this fix?

**Comment by milenaveneziani** [comment]
looks good!

**Comment by xylar** [comment]
Addressed by #287
