### ISSUE TITLE
Creating v0.7 tag

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#299]
I'd like to make a checklist for creating the next release.  Please add/edit as needed

To do:

- [x]  Merge #297 
- [x]  Merge #298 
- [ ]  Update e3sm-unified to v1.1.2 on all E3SM (and ALCC, LANL, etc.) machines
  - [x] edison
  - [x] cori
  - [x] theta (ALCC: OceanClimate)
  - [x] theta (E3SM: ClimateEnergy_2 -- @xylar doesn't have an account yet)
  - [x] rhea (ALCC: cli127)
  - [x] rhea (E3SM: cli115 -- out of space)
  - [x] acme1
  - [x] aims4
  - [x] anvil/blues
  - [x] lanl IC
- [x]  Merge #294 
- [x]  Merge #292

**Comment by xylar** [comment]
@milenaveneziani, are there other things we need to do before we can create the next version tag?  Are you good with these 4 merges being included?  I think the ability to support reference runs is a big improvement that deserves a release.

**Comment by milenaveneziani** [comment]
Thanks for making this list @xylar: it's basically what I have on my whiteboard :) The only other thing I wanted to add myself was the MOC online script, but I will only be able to *start* that before Ocean Sciences, not finish it. So, I'd say let us leave it out for now.

**Comment by xylar** [comment]
No problem, I figured online MOC wasn't quite there.  Mark has been having to turn it off in our runs with ice-shelf cavities, which means that also needs investigation.  Let's plan for online MOC to be part of v 0.7.5 or v 0.8.

**Comment by milenaveneziani** [comment]
> mira (@xylar doesn't have an account)

I think we agreed to take mira off the list, right?
I suppose no news about the cli115 space at olcf?

**Comment by xylar** [comment]
@milenaveneziani, true.  I got mixed messages.  Renata thought e3sm-unified needed to be there.  But it doesn't look like E3SM has any time there this year so I don't even know how I would request access...

What *is* needed is an install of e3sm-unified under the ClimateEnergy_2 project.

**Comment by xylar** [comment]
We're all set.  I'm going to make the tag.
