### ISSUE TITLE
Analysis documentation required (with examples)

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#3]
~~Each analysis notebook should be configured to work with a dataset (in "example-datasets") to produce a desired analysis with output produced in terms of a saved figure(s).  The running of the notebooks operating on example datasets should be specified in a python file in “example-scripts”.  Resultant saved figures are be included in a CORE-level README.md (or perhaps grouped by analysis type for finer granularity) to provide a visual example of the analysis capability.~~

 - [ ] All analysis functions must have an appropriate docstring.
 - [ ] Provide visual examples of MPAS-Analysis capabilities in README.md

**Comment by pwolfram** [comment]
Notebooks have been depreciated, so "notebook" above can be translated to "script".

**Comment by pwolfram** [comment]
I've added some simple checkmark goals for this to hopefully clarify:
>  - [ ] All analysis functions must have an appropriate docstring.
>  - [ ] Provide visual example of MPAS-Analysis capability in README.md

**Comment by xylar** [comment]
Addressed (at least for now) by #158
