### ISSUE TITLE
Make sure analysis scripts do not rely on mesh info present in input files

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#30]
Pretty soon we will default to having no mesh information in output MPAS files. Therefore, we need to make sure that none of our analysis scripts rely on having mesh variables in model files.

A related issue is to make sure that the meshfile (initial condition or restart file) has all the info we need for running MPAS analysis scripts (see for example depth-related fields that are necessary for the OHC calculation).

**Comment by xylar** [comment]
> A related issue is to make sure that the meshfile (initial condition or restart file) has all the info we need for running MPAS analysis scripts (see for example depth-related fields that are necessary for the OHC calculation).

I think this info can still be stored in the analysis members' output files as needed.  It does not need to be in the file used to read the mesh.  It is just that the mesh info (that is, everything in the `mesh` stream, which includes things like `xCell`, `yCell`, `latCell`, `cellsOnCell`, etc.) doesn't need to be stored redundantly in each analysis member's output.

**Comment by milenaveneziani** [comment]
But wouldn't be nice if we had all the mesh information in one single file? This seems even more important to me if we are moving away from storing mesh variables in output files.

**Comment by xylar** [comment]
@milenaveneziani, it seems to me the philosophy of AM output, at least in MPAS-O test cases, is that we want separate streams (therefore separate NetCDF files) for separate AMs.  I would think that only fields that are needed across several AMs should go into the main `output` stream to prevent redundancy.  Anything specific to an AM should have its own stream (and its own NetCDF file(s)).

**Comment by milenaveneziani** [comment]
@xylar: I am a bit lost. What I was thinking about is not AM-specific streams, but mesh-related fields such as refBottomDepth that are not always found in both the initial condition and restart files (at least this is how it used to be a few months. Not sure if things have changed in this respect lately).

**Comment by xylar** [comment]
@milenaveneziani, ah, I see.  `refBottomDepth` and such (`maxLevelCell`, `refLayerThickness` etc.) are not part of the mesh (because it's ocean-specific) so it would need to be included specifically.  I agree that such fields should be in the `output` stream.

**Comment by milenaveneziani** [comment]
@xylar: I disagree about having this information in the output stream. Because we may need the same piece of info in different AM's, and, similarly to having mesh variables in output files, we would be adding superfluous output in different files.
Couldn't we instead have all the information we need for our tools to work (mesh, vertical discretization, component-specific general fields, ..) in one file per MPAS component? 
By 'tools' I include mesh-generator, paraview-extractor, and MPAS-Analysis.

**Comment by xylar** [comment]
@milenaveneziani, I believe all the information you're after has to be in the initial condition file and/or the mesh file.  There is a very specific definition of what it in the mesh file (it's hard coded in MPAS).  Anything not there, e.g. the fields that define the vertical grid, has to be in the initial condition file.  Nearly always, the mesh is also in the initial condition file, but this is not an MPAS requirement so it would be better to look up what the mesh file is in the streams file and use that to get the mesh-specific fields (xCell, yCell, etc.) and then to use the streams file to find the initial condition and use that to find the fields related to the vertical coordinate (maxLevelCell, bottomDepth, refBottomDepth, etc.).

I think it wouldn't be a good idea (and it may be too late) to require that this info be in a single file.  But it has to be in one or both of the mesh and initial condition files or the model wouldn't run.

Does that help clear things up a bit?  If not, maybe I should give you a call so we can chat some more.

**Comment by milenaveneziani** [comment]
Perfectly clear. And indeed my solution in the past has been to cp the meshfile to something that I called gridfile, and then ncks the info I needed from an initial condition file (refBottom, etc) and add them to my 'gridfile'.
I don't think this is the workflow we want.. And now that we are thinking to remove the mesh info from output files, perhaps it's a good time to address this issue, one way or another.
Thanks for sticking with me on this, @xylar.

**Comment by xylar** [comment]
@milenaveneziani, okay, great.  I think we're on the same page now.  I agree that the various tools need to be able to read the the necessary pieces from various sources without causing trouble.  I will try to make sure this is true for the paraview extractor.  Currently, the only field it could potentially make use of that is not in the mesh is `maxLevelCell`, which would need to be in either the file passed with -m or the list of files passed with -f (so it couldn't be from some third file).  It would be great to be able to parse the streams file as part of the paraview extractor, too, so I'll probably steal the code from this repo a soon as we've settled on something we're happy with.

**Comment by pwolfram** [comment]
@milenaveneziani, this could be a tricky issue and we should prepare for this challenge ASAP because it could break the analysis.  Do we have a timeline on when the mesh will be removed from analysis output files?

**Comment by xylar** [comment]
@pwolfram, I believe the mesh info is already not part of the analysis output.  We rely on a data file that Milena put together that includes the mesh and some of the vertical grid info (e.g. `refBottomDepth`).  My understanding is that the best way to handle this would be to look at the streams file to find the mesh and init files that were used, and read the appropriate mesh/vertical grid data from them.  @milenaveneziani, is that consistent with how you see this being handled?

**Comment by milenaveneziani** [comment]
@xylar, @pwolfram: sorry, I missed your last 2 comments on this one!
indeed we are running into trouble now, because sometimes the model output files are transferred from one machine to another for doing the analysis. This can actually happen often, because not everybody has access to the machine where the simulations are performed.
Because of that, the original init file that is in streams.ocean will not be found.

So, we need to think of a different solution.

**Comment by milenaveneziani** [comment]
I just talked with @mark-petersen and he suggested to use one of the restart files. so, we would have to look into the streams file again, but looking for the rst filename.
And then, when transferring the data we still need to make sure that the restart files are transferred as well (or at least one of them).

This in my view is still a bit cumbersome than just having all mesh and vertical coordinate information in one single file, but it is less likely to break things (and we will issue a specific error when the rst file is not found).

What do you think?

**Comment by milenaveneziani** [comment]
Also, should we solve this issue before the current PR to merge the new submodule into ACME analysis is fulfilled?

**Comment by mark-petersen** [comment]
I just spoke with @milenaveneziani about this.  My recommendation is to use the mesh variables in a restart file, rather than the init file.  The restart files are available in the local run directory, and you can use the same python formatting to get the first mpaso.rst.* file.  You don't need access to the remote file space where the init file is kept.  If someone copies analysis files, they only need to remember to copy over a restart as well.  You could check for the mpaso.rst.* file in your analysis scripts, and say "restart file not available" error if it is not there.

Ha - @milenaveneziani and I were typing at the same time.  I need to type faster next time.

**Comment by xylar** [comment]
@milenaveneziani wrote:
> This in my view is still a bit cumbersome than just having all mesh and vertical coordinate information in one single file, but it is less likely to break things (and we will issue a specific error when the rst file is not found).

I think everything we need *would* be available in the restart file.  I agree with @mark-petersen that this would be straightforward to implement.

**Comment by xylar** [comment]
> Also, should we solve this issue before the current PR to merge the new submodule into ACME analysis is fulfilled?

Yes, I do think this should be fixed before we merge this PR.  Similarly, we should figure out the pandas issue you discovered before merging.  I'm really hesitant to merge branches when there are known issues that aren't all that hard to address.

**Comment by milenaveneziani** [comment]
ok, let's do that. We probably won't need the meshfile at all then.

**Comment by pwolfram** [comment]
@xylar and @milenaveneziani, this is somewhat of a moving target because essentially what we are saying is that for vertical grid variables we need to get that information from the

 1. restart file
 2. input file

in that order.  This being said, as far as I can tell that only happens in one place as covered by #67.  Hence, should we close this issue for now, recognizing that new code must follow this convention?  I don't think there is a clean way to verify this unless we put in hard-coded logic into the streams reader, which I do not think is a very good solution.

Note, there is the possibility to simplify the code here and perhaps even pull out this type of operation into its own function because fundamentally all grid information should be in the restart / input file.  As far as I can tell we really don't need the mesh file via `mpas_meshfile` in the config file anymore.  Would you both concur on this?  However, this is clean-up and probably inessential for our current tasks.  Either way, I think we can consider closing this issue in the short-term.

**Comment by xylar** [comment]
@pwolfram, I agree that #67 and preceding commits (I wasn't able to figure out quickly which ones exactly) have dealt with this issue.  The point was not to assume that things like refBottomDepth would be available in analysis member output and I think we're avoiding this everywhere now.
