### ISSUE TITLE
Unification of ocean / seaice scripts

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#31]
Following #29, we will eventually want to simplify functionality used in ocean and sea-ice so that it is shared and more general.

**Comment by pwolfram** [comment]
@xylar and @milenaveneziani, this is along the lines of #8, which we closed because we recognized that this was a moving target.  Here, we may be facing something similar and my inclination would be to close this issue if there are no objections because one could argue that this issue (#31) is essentially a subset of #8.

**Comment by milenaveneziani** [comment]
I may also add that the real issue here is to 'Develop an Interpolation module', which @xylar is planning to work on. Once that is in place, we can have a specific task to unify ocean_modelvsobs and seaice_modelvsobs, and we could call the new function something like MPASregriddeHorSlice.

**Comment by pwolfram** [comment]
@milenaveneziani, do you want specific issues for each of these tasks?

**Comment by milenaveneziani** [comment]
sure, if @xylar is also OK with it.

**Comment by xylar** [comment]
I don't understand what the specific tasks are that @pwolfram wants to make issue for.  In general, I think having too many issues is demoralizing more than it is constructive.  I would rather not treat issues as a "to do" list but rather as a list of things we need to fix (perhaps with some urgency).

**Comment by pwolfram** [comment]
@xylar, I think issues are often used as some type of "to do" list.  Things that need fixed with urgency are labeled with "bug".  I guess it depends on where you want to draw the line, but things that need done for existing code to work well should be listed as issues in my mind.  Addition of new features, however, probably appear once code is written for a PR and an issue isn't necessarily needed.  Hence, work to 'Develop an Interpolation module' would not necessarily require an issue but there could be one if that is helpful.  Use of design docs in either PRs or issues will alleviate this potential problem because the goal is to provide a way to have others discuss the work in a broad way prior to code being written, which is how we have used design documents over the last several years.  We clearly don't want issues for issues' sake.

Are we all closer to the same page here now?

**Comment by xylar** [comment]
@pwolfram, yep, that makes sense.  This repo has more issues by about a factor of 3 than I am comfortable with or than I think is useful.  I think more time should be spent on fixing issues already listed and less should go into posting new issues to the extent possible.  I am frustrated because I feel like too much time is being spent on "process" in this repo and not enough on actually doing work that improves its quality.  But I do agree on your idea of what qualifies as an issue and what doesn't.

Go ahead and post whatever issues related to this closed issue you think are needed.
