### ISSUE TITLE
MOC needs to add bolus velocity

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#310]
By default (and if the appropriate namelist flags are set), the MOC needs to add the bolus velocity to the Eulerian velocity.  This modification is needed for the E3SM v1 MPAS-O paper.

**Comment by xylar** [comment]
We also need to resort to the offline MOC rather than not displaying the MOC at all, since we do not yet support the online MOC.  Otherwise, there is no way to plot the MOC for runs that include the online MOC.

**Comment by milenaveneziani** [comment]
And we do have the bolus velocity in the default output, right?

**Comment by xylar** [comment]
Yes, I believe so.  I'm going to try to put this together tonight.  I don't think it will be hard.

**Comment by xylar** [comment]
Was addressed by #312
