### ISSUE TITLE
ncremap does not work with depth slices

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#315]
When trying to remap depth slices in latlon.  The remapping with ncremap does not work.  I think this is because ncremap assumes the vertical dimension in MPAS is nVertLevels.  In the code the vertical dimension becomes depthSlice

**Comment by xylar** [comment]
Working on this now.

**Comment by vanroekel** [comment]
@xylar your fix worked great for me.
