### ISSUE TITLE
Encoding header got pushed below license header

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#318]
Some of our python files have headers specifying the encoding (when it's unicode instead of ascii).  These are needed when we have special characters like ñ or the degree sign.  When license headers were added, these erroneously were put *above* the encoding header, meaning the encoding now gets ignored.  Oops!

https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/ocean/streamfunction_moc.py#L8

The fix should be easy.  First, we should just manually move the encoding to the top of the file.  Then, we should do the same thing for encoding headers that is done for "shebang" headers in bash/sh/csh scripts within the code that prepends or updates the header.

**Comment by xylar** [comment]
@kevans32, @jhkennedy, just letting you know about this issue since it affects code we took from you.  Presumably you'll run into the same issue down the road, so you'll probably want to pull over whatever fix I come up with.

**Comment by jhkennedy** [comment]
@xylar thanks for the ping, this will be very helpful! LIVVkit hadn't previously used the encoding strings so it wasn't on my radar when I made those scripts. I've been putting them into LIVVkit, so I'll have to tackle this same issue soon.

**Comment by xylar** [comment]
Should be addressed by #319
