### ISSUE TITLE
add capability for EKE and ssh variance analysis

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#323]
For high resolution simulations, plotting of eddy kinetic energy and ssh variance would be useful.  I have a jupyter notebook here https://github.com/MPAS-Dev/MPAS-QuickViz/blob/master/ocean/eke_sshVar/EKE_SSH_stddev.ipynb that could perhaps serve as a starting point.  This capability will require the eddyStats AM to be enabled.

**Comment by xylar** [comment]
I think this would be really straightforward to add.  We could work off of your ARGO task and just change the output variable and the obs (if any), adding a check to make sure `eddyStats` is on.  I'm away until next Thursday but can put this on my list after that.  Let me know if you make progress on it in the meantime.

**Comment by xylar** [comment]
The EKE part of this issue was addressed by #447

The SSH variance is redundant with #278
