### ISSUE TITLE
Selection based on regions

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#34]
It would be good for mpas_xarray efficiency to provide a mechanism to preselect a given region at the preprocessor step prior to xarray concatenation.

Moved from https://github.com/pwolfram/mpas_xarray/issues/16

**Comment by pwolfram** [comment]
[salem](http://salem.readthedocs.io/) may be the solution we have been seeking.

**Comment by milenaveneziani** [comment]
I think this is no longer relevant?

**Comment by pwolfram** [comment]
I think the capability could still be helpful and we really haven't added that functionality if I'm not mistaken, although I need to catch back up on the API so I could be wrong here.

**Comment by xylar** [comment]
We might want a pre-processing step via NCO for this (similar to how we extract time series).  It depends on what exactly you had in mind for this, @pwolfram.  What I understand it that you would define something like a region mask and then you would only get back those cell values that are in the region, not all cells.  This would be useful, for example for computing melt rates under ice shelves more efficiently.  But I'm not aware of a case we've run into so far where we can't do what we want without a capability like this, even at high res...

**Comment by pwolfram** [comment]
Thanks @xylar, I recommend we just sit on this issue for now.  I don't think we need to do anything right now but in terms of efficiency (particularly saving to disk), this will be a useful capability in the long term (e.g., ice shelves applications).  It is fairly likely I will want / need something like this for LIGHT output and may need to add this in a general way to MPAS-Analysis.

**Comment by xylar** [comment]
I looked into salem and its Region Of Interest capabilities require a regular grid (because shapes are rasterized to get a mask) so not appropriate for selecting MPAS regions unless we wanted to first transform data to a regular grid.

I'm looking into efficient ways to create region masks in python for MPAS meshes.

**Comment by milenaveneziani** [comment]
@xylar: is this still relevant?

**Comment by xylar** [comment]
No I don't think so.  I don't think this is the right tool for us.
