### ISSUE TITLE
Add support for online MOC

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#348]
Add support for using the analysis member in MPAS-Ocean for computing the MOC so it doesn't have to be computed (very slowly) in MPAS-Analysis.

**Comment by xylar** [comment]
@milenaveneziani, I'm happy to help but this is one where I think you should take the reins.

**Comment by milenaveneziani** [comment]
I know.. It's on my high-priority list, but a lot depends on a number of other things, high priority as well, which I need to get done by the end of the month.

**Comment by xylar** [comment]
Sorry, I didn't mean to imply that you should get to it right away, just that it isn't something where I would assign it to myself.  I put "priority" on it to indicate that it's a higher priority than other issues.  No stress...

**Comment by milenaveneziani** [comment]
Addressed by #415.
