### ISSUE TITLE
Provenancing of xarray output files

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#35]
Files produced by an xarray save via method to_netcdf should retain information related to how they are generated. This includes at a minimum the machine, script and arguments called, user, and date generated, although there are probably other important criteria too (git hash). This issue should be used to discuss relevant criteria that are useful prior to an implementation of a wrapped to_netcdf function.

See also pydata/xarray#826

Moved from https://github.com/pwolfram/mpas_xarray/issues/5

**Comment by pwolfram** [comment]
Potentially related to #23

**Comment by milenaveneziani** [comment]
Is this still relevant?

**Comment by xylar** [comment]
Yes, we should be updating the history attribute of files we write out to include things like which version of MPAS-Analysis was used to generate them and what command was run and such.  This is still missing.  It hasn't been high on my list, I have to admit, even though it's potentially not good that we're not doing it.

The same essentially applies to the HTML: It should include a comment somewhere with the full details of the run used to create it and the config file used to run the analysis so it could be reproduced later if need be.

**Comment by milenaveneziani** [comment]
I agree this is not a priority, and it probably won't be for some time. Just wanted to make sure whether we were in a position of closing the issue.

**Comment by milenaveneziani** [comment]
> The same essentially applies to the HTML: It should include a comment somewhere with the full details of the run used to create it and the config file used to run the analysis so it could be reproduced later if need be.

We are doing this now. Should we content ourselves with this and close the issue?

**Comment by xylar** [comment]
I think so.  For now, the NetCDF is not considered the primary output and the HTML has a decent amount of provenance.
