### ISSUE TITLE
Redundant observations on theta

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#358]
We have redundant copies of the observations on theta under OceanClimate and ClimateEnergy_2.  This is a pain to maintain so we might want to move all obs to ClimateEnergy_2 unless there are people without access to both.  We would need to update the example config file if we want to go this route.

https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/configs/theta/config.20171031.tenYearTest.GMPAS-IAF.T62_oEC60to30v3wLI.60layer.theta#L120

**Comment by vanroekel** [comment]
@xylar what about moving obs to ```/projects/ccsm/acme``` it would be visible to ClimateEnergy_2 and OceanClimate

**Comment by xylar** [comment]
This is a good plan.  We'd need to coordinate with A-Prime since moving the observations would affect them.  But I think our team are likely the only ones running A-Prime on theta in any case.  Wasn't support just added in a recent PR?

**Comment by milenaveneziani** [comment]
If all obs stay on ClimateEnergy_2 then a-prime is going to be fine.
And yes, I added theta support in the last big PR.

**Comment by milenaveneziani** [comment]
oops, sorry, I didn't read all comments carefully enough.
OK, I will do a quick fix to a-prime once we move the data to the acme directoy.

**Comment by xylar** [comment]
Addressed by #376
