### ISSUE TITLE
mpas-o_in and mpas-seaice_in have changed names again

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#362]
I just tried to run the develop (with the stringIO fix) and found that E3SM master has another name change for the namelist files.  They are now mpaso_in and mpassi_in.

**Comment by milenaveneziani** [comment]
That's true, that is what I used in a-prime just recently. mpassi_in and streams.seaice.

**Comment by milenaveneziani** [comment]
I don't think the related PR was merged yet, right?

**Comment by vanroekel** [comment]
the stringIO PR?  if so, that's true.

**Comment by milenaveneziani** [comment]
No, I mean the E3SM PR with the name changed.

**Comment by vanroekel** [comment]
Yes, that is merged.  The run I point to in #363 is using E3SM master a from May 3rd.

There is another PR that is coming that changes the output file names.  So we now have namelist file changes but all output is still mpascice.XXXX

**Comment by milenaveneziani** [comment]
I am referring to this one: E3SM-Project/E3SM:#2308.

**Comment by milenaveneziani** [comment]
the link didn't come up right, but that's the PR I meant.

**Comment by milenaveneziani** [comment]
changing the filenames won't cause any problem. We only need to have the right namelists and streams.

**Comment by vanroekel** [comment]
Yep, that is the one that changes output files.  This one, which is on master, changed the mpas-o_in and mpas-cice_in names 
https://github.com/E3SM-Project/E3SM/pull/2229

**Comment by xylar** [comment]
Addressed by #363
