### ISSUE TITLE
start and end of sea-ice area/volume time series are ignored if previoulsy run case exists

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#364]
Not sure how to summarize this in the title, but basically, I had run a case with start=1 and end=500, and then subsequently changed the end time to be something less than 500, but I still get plots that go from 1 to 500 years. This only occurs for the sea-ice area and volume time series. The ocean time series are adjusted with the new end time.

**Comment by xylar** [comment]
That's an odd bug but probably an easy one to fix. I'll look into it.

**Comment by xylar** [comment]
Fixed in #365
