### ISSUE TITLE
Consistent color maps for temperature, salinity, potential density, sea-ice properties

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#388]
We use several color maps for temperature and salinity across different analysis plots.  These should be made consistent if possible.

Complaints have been made about `inferno` for sea-ice properties, so maybe an alternative is needed.

Update: I should also add that any other color maps (those we're using for mixed layer depth, velocity components, velocity magnitude, etc.) are up for discussion as well if there's interest.

**Comment by xylar** [comment]
## Options for Temperature

- [ ] thermal
- [ ] RdYlBu_r
- [ ] RdBu_r
- [ ] ...

Examples of `thermal`:
![image](https://user-images.githubusercontent.com/4179064/40165950-9736efa0-59bd-11e8-992b-3bf8846a1afa.png)
![image](https://user-images.githubusercontent.com/4179064/40165958-9fea31e8-59bd-11e8-957b-0e6279283f62.png)
![image](https://user-images.githubusercontent.com/4179064/40165976-a9d97de4-59bd-11e8-9de7-0d9ab4f9689f.png)

Example of ` RdYlBu_r`:
![image](https://user-images.githubusercontent.com/4179064/40166065-e992dc78-59bd-11e8-8486-4b17bdabeecd.png)

Examples of `RdBu_r`:
![image](https://user-images.githubusercontent.com/4179064/40166083-fa06f486-59bd-11e8-8373-99f432585cab.png)
![image](https://user-images.githubusercontent.com/4179064/40166098-052f9c3c-59be-11e8-9f8e-4ddd6c150c1f.png)

**Comment by xylar** [comment]
## Options for Salinity

- [ ] haline
- [ ] RdYlBu_r
- [ ] BuOr
- [ ] ...

Examples of `haline`:
![image](https://user-images.githubusercontent.com/4179064/40166216-4f6af3c8-59be-11e8-97f2-84e75e5aed2c.png)
![image](https://user-images.githubusercontent.com/4179064/40166232-5aa8b1a8-59be-11e8-81a3-03fd1c15007a.png)
http://portal.nersc.gov/project/m2833/mpas_analysis_output/sose_20180209.GMPAS-IAF.T62_oEC60to30v3wLI.cori-knl.afterSalinityFix/ocean/salinSOSE_antarctic_20180209.GMPAS-IAF.T62_oEC60to30v3wLI.cori-knl.afterSalinityFix_depth_bot_ANN_years0008-0013.png

Example of `RdYlBu_r`:
http://portal.nersc.gov/project/m2833/mpas_analysis_output/20180209.G.RRS30to10wLI.Mark.cori-knl.yrs21-30/ocean/sssAquarius_RRS30to10wLI_ANN_years0021-0030.png

Examples of `BuOr`:
![image](https://user-images.githubusercontent.com/4179064/40166337-97b3c6b4-59be-11e8-8483-c167558c5c20.png)
![image](https://user-images.githubusercontent.com/4179064/40166323-8fcd94f2-59be-11e8-9642-2365911c1469.png)

**Comment by xylar** [comment]
## Options for Potential Density

- [ ] `dense`
- [ ] `matter`
- [ ] `Spectral_r`
- [ ] ...

Examples of `dense`:
![image](https://user-images.githubusercontent.com/4179064/40166682-72b82390-59bf-11e8-86fc-ca28f4111b31.png)
![image](https://user-images.githubusercontent.com/4179064/40166691-7bce0be8-59bf-11e8-83be-de47a74f8cf2.png)


Examples of `matter`:
![image](https://user-images.githubusercontent.com/4179064/40166587-2852920e-59bf-11e8-934b-013df05142e8.png)
![image](https://user-images.githubusercontent.com/4179064/40166595-2fa9e958-59bf-11e8-8092-ea910c913d8b.png)


Examples of `Spectral_r`:
![image](https://user-images.githubusercontent.com/4179064/40166642-54133bbe-59bf-11e8-82bb-2d2f6a45b010.png)
![image](https://user-images.githubusercontent.com/4179064/40166656-5eaf7e34-59bf-11e8-8782-fd40924da78a.png)

**Comment by xylar** [comment]
Options for Sea Ice Concentration and/or Thickness:

- [ ] inferno
- [ ] ice
- [ ] ...

Examples of `inferno`:
![image](https://user-images.githubusercontent.com/4179064/40166944-0d799f80-59c0-11e8-9a29-db50803258be.png)
![image](https://user-images.githubusercontent.com/4179064/40166960-17d94fc0-59c0-11e8-89ae-dfe52084610b.png)

Examples of `ice`:
![image](https://user-images.githubusercontent.com/4179064/40166900-fa172700-59bf-11e8-84dd-599eaa82a0ff.png)
![image](https://user-images.githubusercontent.com/4179064/40166923-04b291fe-59c0-11e8-8c92-d5c7403565f0.png)


In both cases, the areas without sea ice could be made dark instead of light for visual consistency:
![image](https://user-images.githubusercontent.com/4179064/40167057-50943aa0-59c0-11e8-990b-713d33baa421.png)

**Comment by xylar** [comment]
@milenaveneziani, @gstreletz @mark-petersen @akturner @darincomeau @pwolfram @vanroekel @matthewhoffman @stephenprice 
We will be staring at these plots for *many* years to come so your input now would be much appreciated.  If you have more suggestions, please add them to the list above.  Please discuss your preference(s) below.

**Comment by xylar** [comment]
My general thoughts are that it's best to avoid a dark-light-dark color map unless the middle value has some meaning (e.g. they make sense for biases or velocity components where zero has a clear meaning).  So it's probably best to avoid maps like `RdBu_r`, `RdYlBu_r`, `BuOr` and `Spectral_r` for all the fields listed here for this reason.

My preferences are:
Temperature: In general, I'm good with `thermal`, though I find it a bit aggressive.  But I really like `RdBu_r` for Antarctica in particular (where it has become a standard).  This is because there is a clear difference between "warm" and "cold" regions.  So I'm inclined to continue to do the Antarctic plots in a non-standard color map.

Salinity: I'm good with `haline`.  I'm not big on either `RdYlBu_r` or `BuOr`.  I'm definitely open to more suggestions.

Potential Density: I lean toward `matter` but I find `dense` to be reasonable.  `Spectral_r` gives the best contrast of the 3 but it highlights densities in the middle of the range, rather than the extremes, which is odd.

Sea Ice Concentration and Thickness: I lean strongly toward `ice`, particularly if we let the background be black as in the example from the [cmocean page](https://matplotlib.org/cmocean/) above.

**Comment by milenaveneziani** [comment]
Here are my thoughts:
1) I am conservative with the temperature colormap, I prefer `RdYlBu_r` for all plots. I love `thermal`, which is similar to `magma` I think, but I use it for MLD in my own scripts to process POP data and I really like it for that.
2) I really like `haline`.
3) I prefer `Spectral_r` for density, I don't mind the contrast in the middle, or `matter`. I am not a fan of `dense`: too little contrast to my eyes.
4) I am not sure about ice, I tend to like `inferno`, but I'd be fine with `ice`. The problem with keeping the no-ice background black is that you waste a lot of color when you print the figures, I tend to avoid the use of dark colors for backgrounds.

**Comment by xylar** [comment]
> The problem with keeping the no-ice background black is that you waste a lot of color when you print the figures, I tend to avoid the use of dark colors for backgrounds.

I guess this is partly a question of what the purpose of these plots is.  I tend to think of them as primarily for viewing on the web and only as a distant second for including in papers or other materials that will be printed out.  It would be easy enough have a `printerFriendly` option somewhere in the config file that defaults to `False` but which would make the background light if set to `True`.

**Comment by stephenprice** [comment]
For temperature I like either RdYlBu_r or RdBu_r. I'm not a big fan of thermal.

For salinity, I think haline is ok, especially if we want something quite diff. than for temperature (e.g., so it is easy to differentiate relative to the temperature maps). BuOr is also ok ... but maybe not so easy to quickly differentiate from temperature if that is important.

I agree w/ Milena on both comments for density colormaps.

For sea ice, I guess that "ice" looks a bit more icy, so that might be nice. I don't think it makes sense to blacken the entire background though. So as in the example concentration plots you have up looks good to me.

**Comment by darincomeau** [comment]
@milenaveneziani I'm also not a fan of thermal for ice thickness :/ - I'd vote to keep 'ice' for that as well.

**Comment by darincomeau** [comment]
@xylar what about colorbars for difference plots? I prefer cmocean's balance to RdBu, and for salinity, I think delta looks nice paired with haline. I can put up a couple sample plots.

For sea ice, I'll also suggest reversing the colorbar on difference plots, so that blue indicates more ice, red indicates less. It seems more intuitive to me, but others please feel free to disagree (@akturner ?).

**Comment by vanroekel** [comment]
My votes would be

1) RdBu_r or RdYlBu_r, The others aren't distinct enough in color range to my eye.  I also think spectral_r could work here.
2) haline is my definite favorite here
3) spectral_r 
4) ice

I would also rather not have dark backgrounds.

**Comment by pwolfram** [comment]
@xylar, I vote for 

1 (temperature). RdYlBu_r
2 (salinity). haline
3 (density). spectral_r
4 (ice). ice

I am opposed to dark backgrounds.  Should we discuss velocity and vorticity field colorbars too now?

**Comment by xylar** [comment]
Okay, I'm seeing:

Temperaute: very few fans of `thermal` or `RdBu_r`, so I think those are out.  There seems to be roughly equal interest in `RdYlBu_r` and `Spectral_r` (with the complication that `Spectral_r` also seems to be preferred for density)

Salinity: A consensus on `haline`

Density: A strong preference for `Spectral_r` (note: `spectral_r` with lowercase `s` is a different color map, which I veto!)

Ice: A strong preference for `ice` but with some concerns that it is single color an therefor has relatively limited perceptual range.

By the way, I think you're all totally wrong about dark backgrounds but I'll defer to the wisdom of the crowd.  As a counter example, though, let me present one of my beautiful velocity magnitude plots:
![image](https://user-images.githubusercontent.com/4179064/40197609-40cffa74-5a14-11e8-8e3a-5fb7c82343f1.png)

I believe @mark-petersen is out and will likely not be able to weigh in.  So I think for now we'll go with:
Temperature: `RdYlBu_r`
Salinity: `haline`
Density: `Spectral_r`
Ice: `ice`

If new alternatives come up that anyone wants to share here, particularly with example plots, feel free.

**Comment by xylar** [comment]
@darincomeau wrote:
> @xylar what about colorbars for difference plots? I prefer cmocean's balance to RdBu, and for salinity, I think delta looks nice paired with haline. I can put up a couple sample plots.

I'm fine with switching to `balance`.  At a glance, it looks pretty similar to `RdBu` but maybe a bit darker at the extremes?  Anyone else want to weight in on the difference plots?

**Comment by milenaveneziani** [comment]
`balance` looks good to me.

About this:
> let me present one of my beautiful velocity magnitude plots

I totally agree that those plots are beautiful, but that's a different situation. I don't like to have dark backgrounds that are meaningless, i.e. just as a solid color background (for example, I even hate the black background terminal windows :).

**Comment by gstreletz** [comment]
I think the current consensus looks good.  My only additional input is that I don't really like thermal, that some diverging colormap (such as balance and delta) should be used for differences, and that existing conventions should at least be considered (I had suggested considering the WOCE colormaps, but there doesn't seem to be much appetite for any of them).

Additionally, I will note that there are several people in CCS-7 who are quite interested in colormaps and who have done a lot of work in this area (as many of you probably know).  They have thought a lot about how to select a colormap for a specific dataset and purpose (e.g., see https://sciviscolor.org/home/colormoves/), and I imagine that some of them would be interested in consulting with us about colormaps, should there be any interest in that.

**Comment by pwolfram** [comment]
I agree with @gstreletz, bringing in CCS-7 (particularly Francesca Samsel) would be a great idea as we decide which colormaps become defaults.

**Comment by milenaveneziani** [comment]
For vorticity, `curl` is fine, but `balance` is better to me. My brain doesn't even have to think twice: negative=blue, positive=red :)

**Comment by xylar** [comment]
These changes are being made in #394.
Here's a link to an example analysis with the new, consistent color maps:
http://portal.nersc.gov/project/m2833/xylar/new_color_maps/20180209.GMPAS-IAF.T62_oEC60to30v3wLI.cori-knl.afterSalinityFix/
