### ISSUE TITLE
Add an inset panel with a map to transect plots

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#390]
The inset would show where the transect is located and would also indicate the start and end (e.g. with `A` and `A'`)

**Comment by milenaveneziani** [comment]
@xylar, @gstreletz: wasn't this done?

**Comment by gstreletz** [comment]
Yeah, this has been mostly ready to go for quite some time, except for some minor issues with plot spacing, title/label overlaps that I wanted to get cleaned up before requesting the merge.  I will get this done and issue to PR by sometime next week.  Sorry for the delay.

**Comment by xylar** [comment]
@gstreletz, any update on this one?  Could you maybe get your branch to a point where you can hand it off to me to finish the PR?
