### ISSUE TITLE
Addition of automatic continuous integration (CI)

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#40]
Now that there are several pytests use of automatic continuous integration will be helpful to automate testing, reduce human testing time, and help ensure that specific design decisions are maintained within the repository.

This issue's purpose is to socialize this idea to determine if it is still too premature to implement automatic CI.

**Comment by pwolfram** [comment]
cc @xylar, @milenaveneziani, @vanroekel

**Comment by xylar** [comment]
@pwolfram, I still don't think the rest of us have a good idea of what CI even looks like.  So I would think the answer is, yes, we should try this out and we'll learn what it is and how it works in the process.  Better sooner than later so we learn to incorporate it into our workflows.

**Comment by mark-petersen** [comment]
@pwolfram I'm interested to learn more about it.  Perhaps use one of the special meeting 10am times for some background on how this works.  This may also fit into the hands-on tutorials that we are planning, but this one would be more advanced than the others.

**Comment by pwolfram** [comment]
@mark-petersen, I think you'll be surprised at how simple this is once set up.  All it does is automate the pytest process we are going through for testing on a case-by-case basis.  Basically, if you take a look at https://github.com/pydata/xarray/pull/1060 it provides the check marks at the bottom of the PR.  I'll try to carve out some time today or tomorrow to get a PR in to set this up to use our existing pytest tests.  I think that may be the cleanest way to go.

We obviously need to provide training on how to write pytests, however, but that is really just the input to CI, which if I understand this correctly, only needs to be set up once.

**Comment by xylar** [comment]
That's pretty cool, @pwolfram!

**Comment by pwolfram** [comment]
See #42 for an implementation

**Comment by pwolfram** [comment]
I'm closing this because we now have CI in this repo from #42.  Please feel free to reopen if you disagree.
