### ISSUE TITLE
Try using new CFTimeIndex in xarray

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#401]
xarray now supports years outside the years 1678 to 2262 that were its previous lower and upper bounds:

http://xarray.pydata.org/en/stable/time-series.html#non-standard-calendars-and-dates-outside-the-timestamp-valid-range

Apparently, this works via calls like:
```python
with xr.set_options(enable_cftimeindex=True):
    ds = xr.open_dataset('long-model-run.nc')
```

**Comment by xylar** [comment]
@pwolfram, have you used this feature yet?

**Comment by xylar** [comment]
Also supports our no-leap-year calendar!

**Comment by pwolfram** [comment]
@xylar, I have not tried this issue.  This was one of the issues limiting our full adoption of xarray and it looks like it is now rectified.
