### ISSUE TITLE
Document when a purge is needed

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#406]
An issue has come up at least twice where analysis behaved unexpectedly when a user didn't purge the output.  We need to carefully document that one should typically use the --purge option unless there is a good reason *not* to, and not the other way around.

**Comment by darincomeau** [comment]
@xylar I have a funny story about this. When I was first running MPAS-Analysis on my run on Theta a couple months ago, I ended up setting the output directory to be the directory above the run directory, thinking it would be nice for bld, run, analysis to all sit next to each other. I then ran with --purge, wiping out the bld and run directories of the simulation. Of course in retrospect this was a stupid place for me to put the analysis output directory, but I was pretty shy about using --purge after that.

**Comment by xylar** [comment]
Hmm, yes, I worry slightly that someone accidentally puts `/` as their output directory and then runs with `--purge`.

In the case you listed above, I think you would have been okay if you had put it inside an analysis directory within your run directory as you suggested.  Then, it would just delete the analysis directory. But I'm guessing you didn't have that extra subdirectory, which is where things went terribly wrong.  Sorry that happened to you!

**Comment by darincomeau** [comment]
No worries - I immediately realized by mistake. I now use it more freely (but there's still a nervous voice in my head).
Could --purge be made to just purge files known to MPAS-Analysis, like rm -rf clim html logs timeseries, etc.? Just a thought.

**Comment by xylar** [comment]
Yeah, good idea.  I just implemented this suggestion and will include it in an upcoming clean-up PR.

**Comment by xylar** [comment]
Documented in #408
