### ISSUE TITLE
HDF5 'Resource temporarily unavailable' error

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#407]
I am seeing the following error.  I believe this might be what @darincomeau saw yesterday (can you confirm?):

```
running: ESMF_RegridWeightGen --source /tmp/z6cz1e4n.nc --destination /tmp/ltgqq_yi.nc --weight /media/xylar/extra_data/analysis/output/GMPAS-QU240wLI/transects_fix_sose/mapping/map_oQU240wLI_to_SOSE_transects_bilinear.nc --method bilinear --netcdf4 --no_log --src_regional --dst_regional --ignore_unmapped
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 139968898306752:
  #000: H5F.c line 491 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1305 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1839 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 940 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
application called MPI_Abort(comm=0x84000000, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```

This seems to occur when I run 2 instances of `run_mpas_analysis` on the same machine and they're doing `ESMF_RegridWeightGen` operations at the same time.  Something about how HDF5 locks files and how this is handled in `ESMF_RegridWeightGen`.

A (suboptimal) solution may be to not start a second `run_mpas_analysis` until the first one is past the stage of generating mapping files, which happens early in the run.

**Comment by darincomeau** [comment]
@xylar yes, this is what I saw yesterday. I'm almost certain I was only running one instance of `run_mpas_analysis` on a particular machine, but did see it on both Theta and Edison. Rerunning with the `--purge` flag, this didn't appear again.

**Comment by xylar** [comment]
I actually think the --purge might be unrelated (unless it killed a job that was still running by deleting the folder it was running on, for example).   Or at least it's not a sure fix.   I encountered this issue while running with --purge but while running an (unrelated) job at the same time.

Anyway, `ESMF_RegridWeightGen` has been odd and frustrating from the start but I don't have an alternative program for generating remapping files.  So we try to tolerate its quirks...

**Comment by xylar** [comment]
Hopefully addressing #413 would also fix this issue.

**Comment by sterlingbaldwin** [comment]
I just ran into this problem on acme1. It was the only job running at the time, the mpas-analysis job spawned from aprime. Below is the complete log output:

```
Computing MPAS climatologies from files:
    mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc through
    mpaso.hist.am.timeSeriesStatsMonthly.0005-12-01.nc
running: ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0001 -e 0005 -i /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//source_symlinks -o /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3
Climatology operations invoked with command:
/usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.0_py2.7_nox/bin/ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0001 -e 0005 -i /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//source_symlinks -o /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3
Started climatology splitting at Thu Jul 19 11:19:07 PDT 2018
Running climatology script ncclimo from directory /usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.0_py2.7_nox/bin
NCO binaries version 4.7.4 from directory /usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.0_py2.7_nox/bin
Producing standard climatology from raw input files in directory /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//source_symlinks
Output files to directory /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3
Climatology from 5 years of contiguous raw data touching 5 calendar years from YYYYMM = 000101 to 000512
Input filenames will be constructed with CESM'ish or E3SM/ACME'ish conventions
Each input file assumed to contain mean of one month
Winter statistics based on seasonally discontiguous December (sdd-mode): DJF sequences comprise three months from the same calendar year
Annotation for CF climatology attribute and climatology_bounds variable will be performed
This climatology will not be regridded
Generating climatology...
Climatological monthly mean for month 1 ...
Climatological monthly mean for month 2 ...
Climatological monthly mean for month 3 ...
Climatological monthly mean for month 4 ...
Climatological monthly mean for month 5 ...
Climatological monthly mean for month 6 ...
Climatological monthly mean for month 7 ...
Climatological monthly mean for month 8 ...
Climatological monthly mean for month 9 ...
Climatological monthly mean for month 10 ...
Climatological monthly mean for month 11 ...
Climatological monthly mean for month 12 ...
Climatological seasonal mean for JFM ...
Climatological seasonal mean for JAS ...
Climatological seasonal mean for ANN ...
ERROR: nco__create() unable to create file "/p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3/mpaso_JFM_000101_000503_climo.nc"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
ncclimo: ERROR seasonal climo cmd_clm[13] failed. Debug this:
 ncra --cb -O -w 31,28,31 --no_tmp_fl --fl_fmt=netcdf4 -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --dfl_lvl=0 --hdr_pad=10000 --gaa climo_script=ncclimo --gaa climo_command="'/usr/local/e3sm_unified/envs/base/envs/e3sm_unified_1.2.0_py2.7_nox/bin/ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0001 -e 0005 -i /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//source_symlinks -o /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3'" --gaa climo_hostname=acme1 --gaa climo_version=4.7.4 --gaa yrs_averaged=0001-0005  /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3/mpaso_01_000101_000501_climo.nc /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3/mpaso_02_000102_000502_climo.nc /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3/mpaso_03_000103_000503_climo.nc /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3/mpaso_JFM_000101_000503_climo.nc

HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 140436507654016:
  #000: H5F.c line 491 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1305 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1839 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 940 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__create()
nco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"

analysis task mpasClimatologyOcean failed during run
Traceback (most recent call last):
  File "/p/cscratch/acme/data/a-prime/python/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 317, in run
    self.run_task()
  File "/p/cscratch/acme/data/a-prime/python/MPAS-Analysis/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 257, in run_task
    outDirectory=climatologyDirectory)
  File "/p/cscratch/acme/data/a-prime/python/MPAS-Analysis/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 455, in _compute_climatologies_with_ncclimo
    ' '.join(args))
CalledProcessError: Command 'ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_dThreshMLD,timeMonthly_avg_activeTracers_temperature,timeMonthly_avg_activeTracers_salinity,timeMonthly_avg_meridionalHeatTransportLat,timeMonthly_avg_meridionalHeatTransportLatZ,timeMonthly_avg_normalVelocity,timeMonthly_avg_vertVelocityTop,timeMonthly_avg_normalGMBolusVelocity,timeMonthly_avg_vertGMBolusVelocityTop --seasons=JFM,JAS,ANN -s 0001 -e 0005 -i /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//source_symlinks -o /p/user_pub/e3sm/baldwin32/testing5/output/diags/piControl/aprime/0001_0005_vs_obs/coupled_diagnostics/20180129.DECKv1b_piControl.ne30_oEC.edison.scratch/clim/mpas//unmasked_oEC60to30v3' returned non-zero exit status 1
```

**Comment by xylar** [comment]
Thanks for letting us know about this problem, @sterlingbaldwin.  It's a really frustrating issue.  I haven't been able to reproduce it reliably enough to try to debug it.  But it clearly has something to do with the more restrictive file locking introduced in HDF5 1.10.x.  If this happens persistently on acme1, that would actually be helpful in figuring out the issue.  What I would need is a simpler case (e.g. a single nclimo call) that reproduces this reliably.

**Comment by sterlingbaldwin** [comment]
This is the first time ive run the newest version of aprime, Im running again now and will let you know if this comes up again.

**Comment by milenaveneziani** [comment]
So, this is more related to the version of HDF5 in e3sm-unified, right?

**Comment by pwolfram** [comment]
@sbrus89, is this the error you saw this morning?

**Comment by sbrus89** [comment]
Yes. I got a very similar error on edison. The partial screen output is below:

`sbrus@nid02679:~/project/DECK_Analysis/DECKv1b_H1/1885-1934> ./analysis.sub 
cmdModule.c(579):ERROR:50: Cannot open file '/usr/syscom/nsg/modulefiles/nsg/1.2.0' for 'reading'
Currently Loaded Modulefiles:
  1) e3sm-unified/1.2.0
/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/cmocean/tools.py:76: MatplotlibDeprecationWarning: The is_string_like function was deprecated in version 2.1.
  if not mpl.cbook.is_string_like(rgbin[0]):
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 46912496620416:
  #000: H5F.c line 491 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1305 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1839 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 940 in H5FD_sec2_lock(): unable to lock file, errno = 524, error message = 'Unknown error 524'
    major: File accessibilty
    minor: Bad file ID accessed
Traceback (most recent call last):
  File "/global/homes/s/sbrus/MPAS-Analysis/run_mpas_analysis", line 265, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/u2/s/sbrus/MPAS-Analysis/mpas_analysis/shared/climatology/remap_observed_climatology_subtask.py", line 131, in setup_and_check
    write_netcdf(ds, obsFileName)
  File "/global/u2/s/sbrus/MPAS-Analysis/mpas_analysis/shared/io/write_netcdf.py", line 50, in write_netcdf
    ds.to_netcdf(fileName, encoding=encodingDict)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/core/dataset.py", line 1137, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/backends/api.py", line 651, in to_netcdf
    autoclose=autoclose, lock=lock)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 280, in open
    ds = opener()
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.0_py2.7_nox/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 204, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2015, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1636, in netCDF4._netCDF4._ensure_nc_success
IOError: [Errno 13] Permission denied: '/global/project/projectdirs/acme/sbrus/DECK_Analysis/DECKv1b_H1/1885-1934/clim/obs/seaIceConcBootstrapNH_JAS_0.5x0.5degree.nc'
ERROR: analysis task climatologyMapSeaIceConcNH: remapObservations_BootstrapJAS failed during check and will not be run
ERROR: a subtask of analysis task climatologyMapSeaIceConcNH failed during check,
       so this task will not be run
`

**Comment by xylar** [comment]
Yes, I think the only change in A-Prime that likely relates is that it now references e3sm-unified 1.2.0, which uses a later version of HDF5.

**Comment by xylar** [comment]
@sbrus89, is this an error you get repeatedly (i.e. is it easily reproducible) or only sporadically?

**Comment by xylar** [comment]
@sbrus89, I typically run with an output directory on `$SCRATCH` or `$CSCRATCH` on Edison or Cori.  Could you try that and see if you get the same thing?  Typically, the analysis isn't something we would want to keep or store in `/global/project/projectdirs/acme/`.  I also think the project space may be a different type of file system that has more trouble with HDF5 locks than the scratch spaces.  More in a moment.

**Comment by sbrus89** [comment]
@xylar , The errors have been easily reproducible for me. 

Thanks for letting me know about the project space. When I run on scratch1 with parallelTaskCount = 1 things seem to work. However, I still get those same errors on scratch1 with parallelTaskCount = 12 (both with ncclimoParallelMode = serial and ncclimoParallelMode = bck).

**Comment by xylar** [comment]
@sbrus89, are your running on a Cori/Edison compute node? Or on a login node?

**Comment by sbrus89** [comment]
@xylar, compute node.

**Comment by xylar** [comment]
@sbrus89 and @sterlingbaldwin, one thing to try would be:
```
export HDF5_USE_FILE_LOCKING=FALSE
```
You'd either set this in your local environment right before calling `./run_mpas_analysis` manually or you'd add it to the job script you run.

If this works, we'll probably need to add this to the example config files here in MPAS-Analysis and also to the bash scripts in A-Prime.

**Comment by sterlingbaldwin** [comment]
After performing three runs one-at-a-time two completed successfully, one had this error again.

**Comment by sterlingbaldwin** [comment]
Im re-running my jobs from yesterday with the HDF5_USE_FILE_LOCKING=FALSE flag, so far everything seems to be working.

**Comment by xylar** [comment]
I really hope that works because I don't have many more tricks up my sleeve.  @sbrus89, any luck?  @sterlingbaldwin, please do keep me posted.  If that fix works consistently, we'll need to make some updates as I said above.  @milenaveneziani, just a heads up that I may need to add this flag to the A-Prime batch scripts.

**Comment by xylar** [comment]
> The first two jobs finished fine, but the third had the error. Although the flag is present in the aprime bash script, I'm not sure how mpas-analysis spawns its subtasks, could it be possible that the environment flags aren't getting passed to the context of each subprocess?

I'm not sure about that but I think the environment gets passed to `run_mpas_analysis`.  @milenaveneziani, do you know one way or the other?  It's almost certainly the case that the environment gets passed from there to the subprocess calls (e.g. `ESMF_regridWeightGen`, `ncclimo` and `ncremap`), as that's the default behavior in the various python subprocess calls.

> Also just a note, I really appreciate some of the touches you guys have added recently. Combing through the log files to find which one contains the errors was a pain, having a print message with the path to the log file for the failed process is really nice.

That was definitely @milenaveneziani's call.  I've found it useful, too.

**Comment by milenaveneziani** [comment]
hmm, we are talking about an environmental variable, right? We have many in a-prime, so I don't see why `HDF5_USE_FILE_LOCKING` would be special in that sense..

> Also just a note, I really appreciate some of the touches you guys have added recently. Combing through the log files to find which one contains the errors was a pain, having a print message with the path to the log file for the failed process is really nice.

thanks, we appreciate you noticing the little improvements.

So, did we do any testing of this (flag) in mpas-analysis outside the a-prime framework?

**Comment by xylar** [comment]
> hmm, we are talking about an environmental variable, right? We have many in a-prime, so I don't see why HDF5_USE_FILE_LOCKING would be special in that sense..

We convert many environment variables into config file options and write them out but I'm not sure we have any other cases where we set environment variables that we expect MPAS-Analysis to use (indirectly by passing them on to NCO).  But I believe we have tested some environment variables related to NCO in the past (like the one that tells NCO not to look in Charlie Zender's home directory) and those worked without any trouble.

> So, did we do any testing of this (flag) in mpas-analysis outside the a-prime framework?

I just tested on Edison and it does seem absolutely necessary there.  @sbrus89 can confirm if that fixed the issue for him (now that we've sorted out the other problems with his particular run).  I think it wouldn't hurt to include it as the default on all machines.

**Comment by milenaveneziani** [comment]
yes, the NCO variable is the only one we use in mpas-analysis, and defining it in run_aprime works.

**Comment by xylar** [comment]
Hopefully the issues seen on Edison will be addressed by #443.  The same does not seem to be true for the issues on ACME1.  I will investigate further as soon as I'm able.

**Comment by xylar** [comment]
@milenaveneziani, I completely agree that we should put it in A-Prime.  Even if it doesn't help on acme1, it will be necessary for batch jobs on NERSC machines.  I assume the only reason we didn't see that already was that we tested on the login nodes?

**Comment by milenaveneziani** [comment]
yes, that is possible. I tested on the compute nodes on anvil, titan and cooley, but not on NERSC machines.

**Comment by milenaveneziani** [comment]
we also set `LD_LIBRARY_PATH` that is needed by mpas-analysis (and e3sm-unified in general) on anvil. That works as well in a-prime.

**Comment by xylar** [comment]
I believe we *unset* `LD_LIBRARY_PATH` on anvil because it interferes with e3sm-unified.  I don't think that relates to MPAS-Analysis directly.  But the NCO flag you mentioned (`export NCO_PATH_OVERRIDE=No`) certainly does.

**Comment by milenaveneziani** [comment]
yes, sorry, `unset` is what I meant.

**Comment by milenaveneziani** [comment]
I now have an a-prime branch with similar changes made in mpas-analysis (flag and modules). Do you want to make a v1.1 now, or do you prefer to include a few more PRs (transect bug fix and the other two)?

**Comment by xylar** [comment]
I don't think anything changed since v1.0 in MPAS-Analysis so far relates to anything that will be standard output in A-Prime.  The example job scripts and config files aren't used.  I don't think you're plotting transects by default, right?  So I would leave MPAS-Analysis the same as it currently is in A-Prime and just add the flag to the batch scripts or the main `run_aprime.bash` script, whichever is appropriate.

**Comment by milenaveneziani** [comment]
yes, you are right, I didn't think it through before asking my question :)

**Comment by czender** [comment]
@xylar and @sterlingbaldwin these are the first reports of file locking issues I have received. One non-ideal fallback may be to call ncclimo in serial mode (ncclimo -p serial) instead of using the background parallelism default. Not a long term solution because serial mode slows things down, and perhaps you already tried that, just making sure you remember that option exists. The problem does seem to be related to treatment of file locking in on netCDF4 files by the underlying HDF5 library. My understanding of this thread is that all problems started occurring after analysis moved to E3SM-unified 1.2.0, which has a different HDF library than the previous E3SM-unified. Is that correct?

**Comment by xylar** [comment]
> My understanding of this thread is that all problems started occurring after analysis moved to E3SM-unified 1.2.0, which has a different HDF library than the previous E3SM-unified. Is that correct?

Yes, that does seem to be the case.

**Comment by xylar** [comment]
I believe this problem has been addressed, either via upgrading of HDF5 libraries on systems or by setting `export HDF5_USE_FILE_LOCKING=FALSE`.  Please re-open if not.

**Comment by chandra04** [comment]
i was wrting a netcdf4 file with python. I had same issue while doing **ncdump filename**, inbetween to verify wether I am wrong or wright.
Suddenly I realised that I hace forgotten the closing the file, once i put the file closing option, all error gone.
