### ISSUE TITLE
Colorbar in Global OHC Anomaly difference plots not centered at 0.

### ISSUE THREAD

**Issue by darincomeau** [MPAS-Dev/MPAS-Analysis#409]
@xylar I noticed in the Global OHC Anomaly set of plots that the difference colorbar has a level at 0, resulting in spurious coloring.

**Comment by xylar** [comment]
Good timing.  I can add this to #408.

**Comment by xylar** [comment]
Here is an example of the problem:
![image](https://user-images.githubusercontent.com/4179064/40506571-802cc944-5f97-11e8-9ce9-95e86abb5627.png)

**Comment by xylar** [comment]
Fixed in #408
