### ISSUE TITLE
Consider switching to new xarray interp() methods

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#422]
See http://xarray.pydata.org/en/stable/interpolation.html

This would apply to vertical interpolation of transects, for which I created my own 1D interpolation.

**Comment by pwolfram** [comment]
It may be worth taking a close look at https://github.com/pydata/xarray/issues/2079 before making a decision.  I'm not sure this tool is general enough to be considered completely robust yet for our uses.  In particular, you can't dump to netcdf with the present implementation and chunking appears to have potential pitfalls.

**Comment by xylar** [comment]
Thanks for the information, @pwolfram.  I'm not sure the chunking would be a problem for us but not being able to output NetCDF is a show-stopper so we'll have to see if that is addressed going forward.

**Comment by shoyer** [comment]
Just to clarify, the merged xarray implementation was written independently of pydata/xarray#2079. It should not effect serialization to netCDF.
