### ISSUE TITLE
Monthly climatology comparisons do not work

### ISSUE THREAD

**Issue by bradyrx** [MPAS-Dev/MPAS-Analysis#425]
Currently, MPAS-Analysis cannot take monthly arguments into `seasons` in a config file. This results in the `ncclimo` command passing the month (e.g. 'Jan') into the `--seasons` flag, which it of course does not recognize as a season.

> ncclimo -4 --clm_md=mth -a sdd -m mpaso -p bck -v timeMonthly_avg_activeTracers_temperature **--seasons=Jan** -s 0001 -e 0010 -i /lustre/scratch3/turquoise/rileybrady    /mpas_analysis_output/BGCtest/clim/mpas/source_symlinks -o /lustre/scratch3/turquoise/rileybrady/mpas_analysis_output/BGCtest/clim/mpas/unmasked_oEC60to30v3

> **ncclimo: ERROR Requested season Jan not defined**

`ncclimo` should instead be computing climatologies for all months and then just skipping the seasonal climatology computation. (@xylar)

**Comment by milenaveneziani** [comment]
Hi @bradyrx. This is because mpas-analysis is based on monthly data already, i.e. it assumes that it is reading in already computed monthly averages.

**Comment by xylar** [comment]
@milenaveneziani, but one should be able to specify `['Jan', 'Jul']` as seasons a it should work.  So I asked @bradyrx to submit this issue.

**Comment by xylar** [comment]
Fixed by #427
