### ISSUE TITLE
interpolation occasionally inserts duplicate values

### ISSUE THREAD

**Issue by gstreletz** [MPAS-Dev/MPAS-Analysis#438]
When interpolating transect data, the interpolator occasionally inserts duplicate values in the results array.  Duplicate values are at points from the original dataset, but do *not* occur at all such points.

To reproduce this problem, run MPAS-Analysis for GeoJSON transects using the two transect files attached, with horizontalResolution = 5, and with upperXAxes=strictlyMonotonic (in order to force failure for these transects to get information written to the log files).  The _strictly_monotonic method of the PlotTransectSubtask class can be modified to print information about duplicates before the ValueError exception is raised (as in the plot_transect_subtask.py file attached).

For the zonal test transect, there is one duplicate point:
duplicate point at 28.459033 degrees latitude
duplicate point at -55.546875 degrees longitude

For the meridional transect, there are two duplicate points:
duplicate point at 2.108899 degrees latitude
duplicate point at -60.930432 degrees latitude
duplicate point at -27.070312 degrees longitude
duplicate point at -15.117188 degrees longitude

[attachments.zip](https://github.com/MPAS-Dev/MPAS-Analysis/files/2207648/attachments.zip)

**Comment by xylar** [comment]
Thanks @gstreletz.  I can reproduce the bug and am working on it.

**Comment by xylar** [comment]
Addressed by #439
