### ISSUE TITLE
Analysis task for plotting regional means and std. deviations of climatologies vs. depth

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#445]
Requires not only climatologies of variables but also variable**2 (to get the standard deviation) if not already in monthly stats.  This likely requires:
* extracting a time series of the 3D variable(s)
* compute the square of the 3D variables
* computing the regional mean of the variables and their squares as functions of time and depth
* computing climatologies of the means and squares
* computing std. deviations
* for each variable and season (e.g., JFM, annual, etc):
  * plotting mean and std. deviation vs. depth

**Comment by pwolfram** [comment]
@xylar, thanks for summarizing.  This looks good to me as a first start.  The one thing that is a little vague is computation of mean / std dev over seasons, e.g., JFM.  I think we want the capability to do the reductions with this level of specificity.  I've updated the description above accordingly. Thanks!

**Comment by xylar** [comment]
As I asked in email, do we need the std. deviation just in time or also in space (i.e. over the regional area)?

**Comment by pwolfram** [comment]
We definitely need the std. dev. in regional space.  I was thinking of it, as well as the mean, as a reduction operator over (regional space, time) that preserves depth-variability, e.g., we could make the depth coordinate parallel.

**Comment by xylar** [comment]
> We definitely need the std. dev. in regional space.

Okay, thanks.  That definitely wasn't clear to me from the start.

>  I was thinking of it, as well as the mean, as a reduction operator over (regional space, time) that preserves depth-variability, e.g., we could make the depth coordinate parallel.

Mathematically, that's a nice feature.  Algorithmicly, I don't think we gain anything by doing depth slices in parallel.
