### ISSUE TITLE
Switch from basemap to cartopy

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#490]
It has been announced that `basemap` is being phased out in favor of `cartopy` and that we should move to `cartopy` as soon as possible:

https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement

- [x] fix tight layout https://github.com/SciTools/cartopy/issues/1207, https://github.com/SciTools/cartopy/pull/1213
- [x] add lat/lon labels on stereographic plots https://github.com/SciTools/cartopy/pull/1089
- [x] apply to global lat/lon plots

**Comment by milenaveneziani** [comment]
oh really?? why.. 
didn't we have some problems with cartopy?

**Comment by xylar** [comment]
There's a lot of discussion, e.g.:
https://github.com/matplotlib/basemap/issues/267#issuecomment-225179958

At some level, I guess the basemap developers decided that the API (the way you interface with basemap when you're writing code) is not as good as cartopy.  So they aren't going to continue development of new features and are phasing out support.  I don't really think we have a choice about this in the long run.

**Comment by xylar** [comment]
We are unlikely to be able to update to python 3.8 until we remove basemap.  basemap relies on proj4 (a rather outdated version of the proj library) but many packages are now being built with proj (replacement for proj4) versions greater than 6 and are unlikely to be build with proj4.

See #651

**Comment by milenaveneziani** [comment]
maybe another reason to inquire about any upcoming new release of cartopy? I mean, it has been a year since their last release..

**Comment by xylar** [comment]
I don't think bugging the developers will do anything but annoy them.  A month ago, they said it would be out by the end of the year...
https://github.com/SciTools/cartopy/issues/1377#issuecomment-543814853

**Comment by milenaveneziani** [comment]
oh, I  hadn't seen that comment, which seems encouraging. Great.
