### ISSUE TITLE
Consider adding Stickler CI to automatically enforce and fix PEP8

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#507]
I have used [Stickler CI](https://stickler-ci.com/docs) on 2 of my personal projects (see below) and have found it to be an effective way to automatically enforce PEP8.  It will add comments for PEP8 issues it can't fix on its own and will add a commit to your PR when it's created or after any commits you push to an existing PR with PEP8 fixes that it can take care of automatically.

@milenaveneziani and @pwolfram, I'd be curious what you think of adding this.

My repos with Stickler CI:
https://github.com/xylar/ismip6-ocean-forcing
https://github.com/xylar/misomip1analysis

**Comment by pwolfram** [comment]
@xylar, it sounds like a good idea.  Can you point us to two examples of this behavior (commenting non-auto fixable issue, autofix issue) so we can see how it works?  I found https://github.com/xylar/ismip6-ocean-forcing/commit/d8beef3960973f404f8418cfe1339806412bf61e for instance but it may be best for you to pick these to show us.

I really like the idea.  As long as it doesn't change the meaning of the code this seems like a great way to ensure we get clean code without the hassle of us dealing with this by hand.  In short, a superb idea assuming it doesn't break code!

**Comment by xylar** [comment]
Here is a PR with examples of both commented corrections and autofix commits:
https://github.com/xylar/ismip6-ocean-forcing/pull/19

In my experience, it never breaks the code.

**Comment by pwolfram** [comment]
I'm trying to see what potential downsides are but to be fair am having trouble seeing any.  This just seems like a win-win approach to ensuring we have good coding standards without a ton of peoples' time and effort.  This being said, I can imagine some folks might not like having their code automatically updated (e.g., they would need to fetch) so there may be some adjustment / education required.  Consensus is obviously key.  Are there any other cons we should consider?  I personally think this is awesome.

**Comment by xylar** [comment]
Yes, exactly.  And that "reviewer" will also push an extra commit to your branch (if necessary) to fix whatever of your mistakes it can.  You'll only get comments on the PR if it can't figure out how to fix it on its own (which seems to happen most often for lines that are too long).

**Comment by milenaveneziani** [comment]
OK, sounds good.

**Comment by pwolfram** [comment]
There may also be a way to disable the automated Sticker CI checking via a tag in the commit message.  I took a quick look but couldn't find an option to disable it for a single commit, e.g., for debugging purposes.
