### ISSUE TITLE
Ncremap for depth-interpolated variables

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#524]
Even after #521, ncremap is not working for 3D MPAS data that has been interpolated to a new depth coordinate or transects (perhaps for the same reason).  This merits further investigation and then perhaps some further generalization of ncremap.

**Comment by czender** [comment]
When you have a chance please shoot me an example of what is not working so I can investigate

**Comment by xylar** [comment]
@czender, I really appreciate you asking about this.  Following the warning messages I'm getting from `ncremap`, I'm taking its advice and transposing my data to `nCells` is the lat dimension and then transposing back.  That seems to be working.  If all goes well, I'll add a pull request to address this tonight.

**Comment by xylar** [comment]
@czender, you're off the hook.  The transpose did the trick and is in #557.

**Comment by czender** [comment]
Maybe not. The forward transpose is a step that ncremap -P mpas always does for MPAS data. There was never a reason to do the reverse transpose until now. ncremap could have a reverse transpose option if desired...

**Comment by xylar** [comment]
@czender, perhaps there was a misunderstanding.  I do the transpose in MPAS-Analysis before calling `ncremap` and then do the transpose back in MPAS-Analysis once `ncremap` has finished.  So the transpose isn't done by `ncremap`.

**Comment by czender** [comment]
I am offering to create an option that takes ...nCells,nVertLevels... data, transposes it, regrids it, and transposes it back to ...nCells,nVertLevels... order. Right now -P mpas does the first transpose not the second. And plain ncremap does neither transpose. So if it would be useful/faster, ncremap -P mpas2, e.g., could do both transposes.

**Comment by xylar** [comment]
Ah, I see.  Thanks, but I think the solution in #557 is a lot simpler for both of us for now.  If there's ever interest in remapping fields of this type outside of MPAS-Analysis, that might definitely be worth considering.  But I need to do several other operations like renaming dimensions and adding new coordinates after these remaps, so I might as well transpose and transpose back as well.

**Comment by czender** [comment]
Sounds good.
