### ISSUE TITLE
Possible issue with MOC

### ISSUE THREAD

**Issue by jonbob** [MPAS-Dev/MPAS-Analysis#540]
I got the following output from a recent run of mpas-analysis on anvil:
![moctimeseries_20190124 gmpas-iaf base rrs30to10v3 anvil](https://user-images.githubusercontent.com/13684848/53513469-8602ca00-3a82-11e9-80f9-6fb3b8dc5cd2.png)
No other output showed a discontinuity at year 23, which makes me think it could be a problem with the MOC calculation. The output from the analysis can be seen at [20190124.GMPAS-IAF.base.RRS30to10v3.anvil](http://portal.nersc.gov/project/acme/jonbob/20190124.GMPAS-IAF.base.RRS30to10v3.anvil/html/), and the output from the run itself is available on anvil at: ```/lcrc/group/acme/jwolfe/acme_scratch/anvil/20190124.GMPAS-IAF.base.RRS30to10v3.anvil/run```

**Comment by xylar** [comment]
@milenaveneziani and @mark-petersen, you have more familiarity with this calculation than I do.  Any idea how this could happen?  Are you able to work with @jonbob to dig into it?  It would be important to know if this is indicative of a problem with the high-res simulation, a data output glitch, or an issue with the MOC analysis calculation.

**Comment by milenaveneziani** [comment]
I ran the analysis just today on the HR run, and haven't had this problem. Seems like the whole thing got shifted upward for year 23 in this case..
@jonbob: I suppose you are using the online MOC for this plot?

**Comment by jonbob** [comment]
@milenaveneziani - did you run the analysis on this HR case? Or a different one? I'm not sure what you mean by online MOC -- the output came from MPAS-Analysis

**Comment by milenaveneziani** [comment]
no, the 18to6.
I checked the run/ directory for this run, and it seems that the online MOC analysis member is turned off for this run, so the MOC is being calculated offline. Could you please point me to the output directory of the analysis (where all the plots/climo data/etc are)?

**Comment by jonbob** [comment]
on anvil at 
```/lcrc/group/acme/jwolfe/case_output/20190124.GMPAS-IAF.base.RRS30to10v3.anvil```

**Comment by milenaveneziani** [comment]
Jon is restarting the analysis after a purge. Hopefully that is all that is needed for this.

**Comment by xylar** [comment]
@milenaveneziani and @jonbob, did rerunning the analysis after a purge make any difference?  If not, I think @milenaveneziani should try running the same analysis with your config file (just `streamfunctionMOC`) and see if she can track down the source of the problem.

**Comment by milenaveneziani** [comment]
@xylar: @jonbob reran the whole thing after a purge and no, there was no difference in the MOC result. The problem emerges because of 3 weird (order 100Sv) MOC values during year 23: the ones for months Jun-Jul-Aug. Since we plot the 1-year running averages, those 3 values affect the whole time series for that year. I am thinking there is something weird with the timeseriesStats data, although we looked at the global stats and nothing particularly unusual comes up..
