### ISSUE TITLE
Degree bounds not being adjusted in WOCE transects

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#546]
I just realized that the degree bounds that we print on the top axis of the transects, are not being adjusted when a subset of the transect is plotted (WOCE transects; see #539).
See this for example:
![image](https://user-images.githubusercontent.com/8237579/53664340-7bcd0100-3c25-11e9-8470-5b3182786191.png)

**Comment by xylar** [comment]
Oops, I meant to check that. Should be an easy fix.
