### ISSUE TITLE
Incorrect value of nVertLevels used in for temperature in ocean_modelvsobs

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#56]
When reading time series data for ocean_modelvsobs, nVertLevels=1 is used when it should be zero.  This only occurs in this file/subroutine and for temperature.

**Comment by vanroekel** [comment]
addressed in #57

**Comment by pwolfram** [comment]
See also #52 for discussion related to discovery of bug

**Comment by pwolfram** [comment]
Resolved via #57 merge...
