### ISSUE TITLE
new analysis: regional OHC time series

### ISSUE THREAD

**Issue by matthewhoffman** [MPAS-Dev/MPAS-Analysis#571]
An idea for new analysis item: regional OHC time series.  Inspired by 
Timmermann, R., & Hellmer, H. H. (2013). Southern Ocean warming and increased ice shelf basal melting in the twenty-first and twenty-second centuries based on coupled ice-ocean finite-element modelling. Ocean Dynamics, 63(9-10), 1011-1026.  https://link.springer.com/content/pdf/10.1007%2Fs10236-013-0642-0.pdf

> To analyse the ocean heat content in regions that are
expected to influence ice shelf basal melting, we divide
the Southern Ocean into sectors referred to as “Weddell
Sea”, “Bellingshausen Sea”, “Amundsen Sea”, “Eastern
Ross Sea”, and “Western Ross Sea” (Fig. 3). Each of the
sectors is subdivided into a “shelf” and a “deep” sector,
with the boundary along the 800-m isobath in the Weddell and Amundsen Seas and along the 700-m isobath in
the other sectors. Mean temperatures are computed between
200-m depth and the bottom on the continental shelf and
between 400 and 1,000 m for the deep subsectors. The rationale behind this choice is (1) to exclude short-term variations that are most pronounced in surface waters and (2) to
mainly consider water that has the potential to enter the shelf
from the deep sectors and the subice cavities from the shelf
subsectors

**Comment by xylar** [comment]
I've had this on my to-do list for almost 2 years now, but keep having to put it off.  Good to have an issue for it.

**Comment by xylar** [comment]
Here's the figure for reference:
![image](https://user-images.githubusercontent.com/4179064/56607086-fd2e8780-6607-11e9-9b12-7a022471ec32.png)
There's an equivalent for salinity that we should also do.

They call it OHC in the paper but it's really mean temperature (which is presumably more useful for comparison, since volumes would inevitably differ between models).

**Comment by milenaveneziani** [comment]
This goes along with doing T,S trends with depth, regionally. Again, we have had it on our plate for a while, but of course having to write a paper is a good incentive for new analysis :)

**Comment by xylar** [comment]
Yes, all that this really should require is defining GeoJson shapes for the different regions (the hard part is separating the part on and off the continental shelf) and then running my tool to make region masks for the grids we want to support.  From there, it's essentially the same code as the melt-rate time series.

**Comment by xylar** [comment]
I'd estimate that this is about 1 days' work.

**Comment by milenaveneziani** [comment]
And we already have the ocean basin regions. We just need to define the SO subregions, which was another thing on my to-do list..

**Comment by matthewhoffman** [comment]
@xylar and @milenaveneziani , thanks for your discussion on this.  After digging into some new analysis for the Cryosphere runs, maybe it is a better use of time to postpone these ideas until our understanding of the critical things to look at are a little more mature.  I don't want to make more work for people until we know that those sorts of analyses are going to be useful.

**Comment by milenaveneziani** [comment]
I am sure we'll need this for our papers though, if not right now, by the summer for sure.

**Comment by xylar** [comment]
I agree, it should be a priority.  The tricky bit is splitting the polygons for the regions at the shelf break.  Here's a code snippet that extracts an isobath.  We could use something like this to get the 1500m isobath from Bedmap2 and use that shape to split the polygons.

https://github.com/kthyng/arpae/blob/master/plots.py#L68-L76
