### ISSUE TITLE
Add plots for min/max MLD

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#573]
Following https://github.com/MPAS-Dev/MPAS-Model/pull/209, min and max values over a month will be available in some MPAS-Ocean runs.  This is likely to be particularly useful for MLD.

Some analysis should be added to take advantage of this.

**Comment by xylar** [comment]
@vanroekel, what do you foresee as being useful plots?  Should one compute the max/min over the full climatology interval and plot that?  Or a climatology of the monthly max/min? Or something else?  How were you planning to use these (outside of MPAS-Analysis)?

**Comment by vanroekel** [comment]
I think most useful would be climatologies (seasonal is likely fine) of dThreshMLD, tThreshMLD, and boundaryLayerDepth.  I would suggest a straight climatology of the max/min is the most useful diagnostic.  I think other variables would be a more specialized use case.  @milenaveneziani  and @maltrud what do you think?

**Comment by milenaveneziani** [comment]
Agree with @vanroekel: climatologies of max/min mixed and boundary layer depths would be great for general MPAS-Analysis.

**Comment by xylar** [comment]
Sounds good.  Definitely easier than anything fancier.

Right now, we're only doing plots of climatologies of `timeMonthly_avg_dThreshMLD`.  Do we want to add corresponding plots of mean `tThreshMLD` and `boundaryLayerDepth` as well?  Also, how do we want to group them? min/mean/max closest together for a given field and season, right?  Then, the next season?  And separate galleries for dThreshMLD, tThreshMLD, and boundaryLayerDepth?

**Comment by milenaveneziani** [comment]
> Do we want to add corresponding plots of mean `tThreshMLD` and `boundaryLayerDepth` as well?

I'll leave that up to @vanroekel.

> how do we want to group them? min/mean/max closest together for a given field and season, right?

The mean plots we compare with obs, so perhaps we want to keep those separate. I would do min/max (lower/upper plots) for different season, for `dThreshMLD` (or each variable).
