### ISSUE TITLE
Clean return for specific analysis if a specific AM turned off in model

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#58]
Should we add a check on whether the needed AM for the analysis was turned on? 

For example, we will always need `timeSeriesStats`, but of course we'll want specific AM's for metrics such as the OHC, MOC, etc.

cc @milenaveneziani and @xylar

**Comment by xylar** [comment]
@pwolfram, yes, I think this is important.  It's a subset of #18, and I think it makes sense to have more specific issues that can be addressed with a single PR like this one and as opposed to #18.

**Comment by xylar** [comment]
My solution for task parallelism, see the design document in #112, should also handle this issue.

**Comment by pwolfram** [comment]
This should be addressable via improvements proposed in #127, correct @xylar?

**Comment by pwolfram** [comment]
On second thought we may need something else but it may be worthwhile building this functionality into the task base while we are thinking about what constitutes a particular "analysis".

**Comment by xylar** [comment]
#127 / #128 don't address this directly but the `setup_and_check` function is intended precisely to address this issue.  Together with some checks that @milenaveneziani has put into #139, I think this should be able to be addressed.

**Comment by xylar** [comment]
Addressed by #129 and some subsequent clean up.
