### ISSUE TITLE
Timeseries plots start from year 1 even if timeseries_yr1 is not 1

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#59]
I think I only noticed this in the sea-ice time series, not OHC or SST.

**Comment by xylar** [comment]
@milenaveneziani, I can reproduce this issue.  It does, indeed, seem to be only for sea-ice time series and only for some of them.  Should be easy to track down and fix.

![iceareacellnh_20161117 beta0 a_wcycl1850 ne30_oec edison_b1850c5_ne30_v0 4](https://cloud.githubusercontent.com/assets/4179064/21110105/d58d2b00-c050-11e6-8fd5-af6d70961eeb.png)
![iceareacellsh_20161117 beta0 a_wcycl1850 ne30_oec edison_b1850c5_ne30_v0 4](https://cloud.githubusercontent.com/assets/4179064/21110107/d58d8c30-c050-11e6-938c-7ac59dd60ba1.png)
![icevolumecellnh_20161117 beta0 a_wcycl1850 ne30_oec edison_b1850c5_ne30_v0 4](https://cloud.githubusercontent.com/assets/4179064/21110104/d58bf2bc-c050-11e6-8659-79df7b8557ce.png)
![Uploading iceVolumeCellSH_20161117.beta0.A_WCYCL1850.ne30_oEC.edison_B1850C5_ne30_v0.4.png…]()

**Comment by milenaveneziani** [comment]
how weird that SH ice volume doesn't have it..

**Comment by xylar** [comment]
It seems to also be missing any reference to the black curve.  I wonder if the two are related.  I haven't had time to investigate further.  Hopefully later in the week...

**Comment by milenaveneziani** [comment]
Solved by #61.
