### ISSUE TITLE
Allow expanded Antarctic stereo width for SOSE comparison

### ISSUE THREAD

**Issue by bradyrx** [MPAS-Dev/MPAS-Analysis#596]
There is a config option for the stereo width for Antarctic projections (`comparisonAntarcticStereoWidth = 6000.`). Changing this has no effect on the SOSE observational comparison, since the SOSE output is fixed at 6000km:

https://github.com/MPAS-Dev/MPAS-Analysis/blob/375e780f37927dee241821f7d9a24b07544ab723/mpas_analysis/ocean/climatology_map_sose.py#L199-L202

My understanding is that the SOSE domain is to 30S, so it must be sliced in pre-processing, although I couldn't pin down the location of this in the pre-processing scripts. A larger radius for the SOSE data would be desirable for folks thinking about the Southern Ocean and ACC. 

Here's a demo of what I get out of `mpas-analysis` by expanding the stereo width to 10000:

![image](https://user-images.githubusercontent.com/8881170/58511014-31d9b580-8157-11e9-923e-7ec2f5e2479e.png)
![image](https://user-images.githubusercontent.com/8881170/58511052-4a49d000-8157-11e9-932e-368f7cca946c.png)

This works for BGC, since we're using global observations.

![image](https://user-images.githubusercontent.com/8881170/58511099-62b9ea80-8157-11e9-9684-936633bd05bb.png)

**Comment by xylar** [comment]
@bradyrx, I understand the frustration.  I don't have a good solution for this.

It is too time consuming to remap these observations per MPAS-Analysis run.  Remapping was performed to the default Antarctic grid using `config.default`:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/preprocess_observations/preprocess_SOSE_data.py#L520
which is used to create a remapper to the 6000x6000 Antarctic grid:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/preprocess_observations/preprocess_SOSE_data.py#L538

With a non-trivial amount of work we could make the default Obs data set larger and crop it to the smaller 6000x6000 that we typically use.  However, the data are already among the larges data sets we provide so I hesitate to perhaps double this size.

@milenaveneziani and @maltrud, do you have thoughts?

**Comment by xylar** [comment]
@bradyrx, you could run the https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/preprocess_observations/preprocess_SOSE_data.py script yourself and just modify it here:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/preprocess_observations/preprocess_SOSE_data.py#L538
to set the size of the grid you want.

You'd then need to modify the SOSE task to (optionally) use that new resolution.

**Comment by xylar** [comment]
One more follow-up.  I can add a set of SOSE data to the repo with a domain of 10000x10000 that wouldn't get downloaded with the download_analysis_data script but which could be downloaded manually.

I can then change the SOSE climatology maps to optionally take a domain size for the SOSE data.  I think that would take care of this for both our need and yours @bradyrx.  I won't get to this until Sunday or sometime next week, since I'm on vacation.

**Comment by bradyrx** [comment]
Thanks for all the comments @xylar. I see the problem here, especially with processing time. Let me know which of the last two options makes more sense. I think the latter is most straightforward on my end and gives the option to future users to have 10,000km radius (which covers much of the Southern Ocean).

No rush on this -- take your time. I appreciate the help.
