### ISSUE TITLE
Copy diagnostics and add example config/job script for CompyMcNodeFace

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#598]
E3SM-Unified has been installed there.

To do:
- [x] copy public obs, mapping files and region masks
- [x] copy private obs, etc.
- [x] find an appropriate E3SM run on compy
- [x] add an example config file for the run
- [x] add and example job script

**Comment by xylar** [comment]
Add config file for run at /compyfs/vanr302/e3sm_scratch/GM600_20190624_GMtest_constant_intel.compy/run

**Comment by xylar** [comment]
@vanroekel, do you have a config file for this run?
https://portal.nersc.gov/project/acme/lvroekel/20190711.testLuke.A_WCYCL1850S.ne30_oECv3.compy_yr_30_40/

Also, is that a run you would likely keep around on compy so it could be used for testing analysis?  Or is it a one-off that you'll archive and delete soon?

**Comment by vanroekel** [comment]
@xylar that run should exist for awhile.  I don't imagine it being deleted soon.  I've just made a PR based on it.
