### ISSUE TITLE
Analysis on historical data raise errors

### ISSUE THREAD

**Issue by chengdang** [MPAS-Dev/MPAS-Analysis#607]
Hi. I'm hoping to apply MPAS-analysis to a pair of historical simulations from the year 1985 to 2014 on cori-knl, and got the following errors from doing model vs observation comparison:

> climatologyMapSSH_remapObservations.log:TypeError: ufunc multiply cannot use operands with types dtype('<M8[ns]') and dtype('float64')
> timeSeriesOHCAnomaly_computeAnomaly.log:ValueError: The data set contains no Time entries between dates 1850-01-01 00:00:00 and 1850-12-31 23:59:59.
> timeSeriesSalinityAnomaly_computeAnomaly.log:ValueError: The data set contains no Time entries between dates 1850-01-01 00:00:00 and 1850-12-31 23:59:59.
> timeSeriesTemperatureAnomaly_computeAnomaly.log:ValueError: The data set contains no Time entries between dates 1850-01-01 00:00:00 and 1850-12-31 23:59:59.

Any suggestions on how to fix these? or, how should I skip the last three comparisons so mpas-analysis can still generate HTML files? Thank you.

**Comment by stephenprice** [comment]
Cheng - someone else likely has a better answer regarding how to fix the errors (so you actually get the time series outputs). But if you are trying to get around those errors for the short term you can remove the time series plots and generate the rest of the analysis by looking for the line in the .config file like: 

generate = ['all', 'no_eke', 'no_BGC', 'no_icebergs']

... and adding in:

'no timeSeriesOHCAnomaly', 'no timeSeriesSalinityAnomaly', 'no timeSeriesTemperatureAnomaly'

**Comment by xylar** [comment]
@chengdang, could you point me to your config file and your analysis output?  From the error messages, it looks like you're using a reference year of 1850, which is not part of the simulation output you're trying to analyze.  The reference year should be set to the first year of output you have.  That would explain the errors in the time-series anomalies but not in remapping the SSH observations.  I'm not yet sure what's wrong there.

@stephenprice's solution of disabling the analysis is a good temporary fix.

**Comment by xylar** [comment]
Here's specifically what I'm referring to with the reference year:
```
[timeSeries]
## options related to producing time series plots, often to compare against
## observations and previous runs

# the year from which to compute anomalies if not the start year of the
# simulation.  This might be useful if a long spin-up cycle is performed and
# only the anomaly over a later span of years is of interest.
anomalyRefYear = 1850
```
where I'm guessing you have set this to 1850, but that data from 1850 is not available in your simulation output.

**Comment by xylar** [comment]
The first error was reported already here (by you, thanks!):
https://github.com/MPAS-Dev/MPAS-Analysis/issues/525
and fixed here:
https://github.com/MPAS-Dev/MPAS-Analysis/pull/526

So if you use MPAS-Analysis 1.2.1 or later, that one should go away.  One option is to clone the latest `develop` version version from GitHub.  Another is to wait for me to update `e3sm-unified` to v1.2.6, which will include the latest MPAS-Analysis (1.2.4, which I hope to release this weekend).

**Comment by chengdang** [comment]
Thank you, Steve@stephenprice and Xylar @xylar.
Somehow I forgot the first error report. I'm running it again using 1.2.1, and all errors are gone.

But the config file I use only define the start_year and the end_year of time series comparison, it does not define anomalyRefYear. Is the following config correct? 

> [timeSeries]
> ## options related to producing time series plots, often to compare against
> ## observations and previous runs
> # start and end years for timeseries analysis. Using out-of-bounds values
> #   like start_year = 1 and end_year = 9999 will be clipped to the valid range
> #   of years, and is a good way of insuring that all values are used.
> startYear = 1985
> endYear = 2014

**Comment by xylar** [comment]
@chengdang, If you don't explicitly define the simulation start time in the config file, it it taken from the variable `simulationStartTime` in the first restart file that `MPAS-Analysis` can find in your simulation directory.  If you do an ncdump -v simulationStartTime on the earliest restart file, I bet you will find that variable is saying the simulation started in 1850.  This is probably because you are continuing a historical run at 1985 that was run previously from 1850.

The solution is simply to define
```
[timeSeries]
...
anomalyRefYear = 1985
```
in your config file.  That will override `simulationStartTime` with the beginning of 1985 for purposes of computing anomalies.

Glad switching to a later MPAS-Analysis worked for you.  I would suggest you update to the latest.  If you're using a conda environment, it might be worth creating a new one for the latest package version (1.2.4, which I just released).  If you're using the repo, do a `git fetch --all -p` and then a hard reset to the latest `master` or `develop` (currently identical).

**Comment by xylar** [comment]
@chengdang, please close this issue of the above suggestion addresses your issue.  If not, let me know and we can investigate further.

**Comment by chengdang** [comment]
@xylar  Thank you! I am able to run the time series analysis with your suggestions. I'll close this issue.
