### ISSUE TITLE
make verbose true by default?

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#648]
I would like to suggest making verbose the default behavior.  I nearly always run with that flag and it is frustrating when I forgot to have waited in the queue for multiple hours only to see no reasons for failure.  

It is also likely I'm missing reasons for why this is off by default.  Please let me know if this is the case.

**Comment by xylar** [comment]
@vanroekel, when things fail during the "setup-and-check" phase in MPAS-Analysis, it's often desirable that the task simply doesn't run.  It gives users the impression that something has gone wrong when the desired behavior might just be to disable the task and move on.

There's currently not a way to distinguish tasks that fail for an "acceptable" reason and ones that fail for a "catastrophic" reason during the setup phase.  As a result, it is not at all clear whether a "quiet" or "verbose" mode is more useful.

Up to now, users have reported finding it disconcerting to see verbose reports of non-catastrophic setup errors (e.g. if you didn't explicitly exclude tasks with land-ice cavities but they're not in your run)  that give the impression the analysis is not running successfully.  See #504 and #519 

I often run with the same `generate` flags for runs with and without melt rates, meaning that the analysis related to melt rates fails during setup.  This is convenient so I don't have to worry about which runs are which when I'm generating config files from a template.  So I find it convenient to not have verbose output quite a bit more often than I explicitly *want* the verbose output for debugging.

However, I'm open to changing to a `--quite` tag and having "verbose" be the default.  This would mean that I and other "lazy" users that don't explicitly disable analysis that is expected to fail during setup would need to get used to using the `--quiet` flag most of the time.

@milenaveneziani, @matthewhoffman, @stephenprice and @darincomeau, as frequent users of MPAS-Analysis, what would your preference be?

@sterlingbaldwin, as the person who I believe originally brought #504 to my attention, how would you feel about making this switch in `processflow`?

**Comment by vanroekel** [comment]
@xylar thank you for the detailed explanation!  This makes a lot more sense.  I did not know verbose will fail a task if a trace is generated.  Given what you say, I'm happy leaving as is, especially if others prefer this way.

**Comment by darincomeau** [comment]
I prefer things the way they are now, but it's not a strong preference.

**Comment by xylar** [comment]
@vanroekel, just to be clear, `--verbose` doesn't cause tasks to fail any differently than without it.  It's just that tasks may fail during setup for benign reasons but they still generate a stack trace that looks like something catastrophic happened.  This has confused users more than suppressing potentially undesirable failures seems to do, especially when `--verbose` is available in case debugging is needed.

**Comment by vanroekel** [comment]
I see now.  It seems like you are more likely to be contacted over benign failure confusion than forgetting to put in the flag for debugging.  I think I will close this issue.  Thanks for explaining this to me.

**Comment by milenaveneziani** [comment]
I personally use `--verbose` when I am running diags on a completely new setup/run, and then I am almost 100% positive that I am screwing something up the first time around :D
