### ISSUE TITLE
Not compatible with xarray 0.14.1

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#661]
xarray 0.14.1 just came out today and we don't seem to be compatible.  I've put in a pull request to constrain mpas-analysis 1.2.6 to xarray <0.14.1: https://github.com/conda-forge/mpas-analysis-feedstock/pull/11

I will work on fixing the incompatibilities later today.

**Comment by dcherian** [comment]
Can MPAS-Analysis test against xarray master to avoid these situations in the future?

**Comment by xylar** [comment]
@dcherian, I will think about that.  It's quite a bit more complicated to test against `master` than to just install a conda package.  Or do you have a conda package with the current master somewhere?

**Comment by dcherian** [comment]
xgcm does this with travis: 

https://github.com/xgcm/xgcm/blob/3151dd361b37e6e81ed0fe00b866bd138be30776/ci/environment-py37-upstream-master.yml#L1-L13

**Comment by xylar** [comment]
@dcherian, thanks!  That looks easy enough.  I'll give it a try.

**Comment by xylar** [comment]
@dcherian, that doesn't look like it will work in our case, see https://travis-ci.org/MPAS-Dev/MPAS-Analysis/jobs/614698429#L139

xarray is getting installed from conda because some of our dependencies also depend on xarray.  Then, presumably xarray gets clobbered via pip with the version from master but I doubt that's a clean process.  Any suggestions there?

**Comment by xylar** [comment]
Actually, maybe it's fine.  It looks like it does uninstall xarray 0.14.1 before installing master:
https://travis-ci.org/MPAS-Dev/MPAS-Analysis/jobs/614698429#L495-L499
```
Installing collected packages: xarray
  Found existing installation: xarray 0.14.1
    Uninstalling xarray-0.14.1:
      Successfully uninstalled xarray-0.14.1
Successfully installed xarray-0.14.1+2.g6b70107a
```
Thanks again fro the suggestion.

**Comment by dcherian** [comment]
yay! :+1:
