### ISSUE TITLE
analysis_task checks for ocean data availability even if only sea-ice tasks are requested

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#665]
I guess my title says it all :)
I ran a recent case where I only had sea-ice output files available for say, years1-years2, not ocean output files. I then requested to compute sea-ice only climatologies and time series over those years, and I received an out-of-index error.
After some debugging, I realized that that happened because it was checking ocean data availability, not just sea-ice's.

**Comment by milenaveneziani** [comment]
From @xylar's email:

> The way it works, see here:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/e73db924f8d19480bfcbdc0502dccb939ecb8aa3/mpas_analysis/__main__.py#L75-L77
is that it updates the bounds based on which files are available for each component, so it makes sure files are there for both ocean and sea ice.  If you only had ocean or sea-ice files, it would be fine but if you have both, they have to cover the same time.
I'm to sure if there's an easy way to change this because we use the same time bounds for all components.

so, I'd say, let us forget about it.

**Comment by xylar** [comment]
The problem is we need to set these bounds before we know whether a given task will run or not, so there's not a way to know which tasks are requested at the point where we set the time bounds.

**Comment by xylar** [comment]
The reason for this was that it's dangerous for individual tasks to set the time bounds and then have others try to do the same, possibly not in a consistent way.

**Comment by milenaveneziani** [comment]
I see. Thanks for clarifying. I am going to close this.

**Comment by xylar** [comment]
You could leave this open if it's useful to have a separate set of climatology and time-series bounds for different components.  I would say the easiest in these unusual cases might be to point the ocean history to an empty directory, so it finds sea-ice files but not ocean files.

**Comment by milenaveneziani** [comment]
yeah, never mind, I think there is a good explanation to leave it as is. I just wanted to make sure it wasn't a recently introduced bug, since I have never run in this situation before.
