### ISSUE TITLE
Sea ice concentration colorbar label should be 'fraction'

### ISSUE THREAD

**Issue by matthewhoffman** [MPAS-Dev/MPAS-Analysis#70]
Currently, the plots for sea ice concentration have values that range from 0.0-1.0 but the label on the colorbar is "%". The label should be changed to "fraction" (or the values changed from 0-100).

Attached screenshot shows example:
<img width="269" alt="screen shot 2017-01-09 at 10 44 24 am" src="https://cloud.githubusercontent.com/assets/4182034/21777118/cbae0418-d65a-11e6-82aa-32ebd5695f5f.png">

**Comment by pwolfram** [comment]
@matthewhoffman, I'm happy to do the one-line PR for this but obviously you have first rights to this if you want.

**Comment by xylar** [comment]
Thanks @matthewhoffman!
