### ISSUE TITLE
Analysis system creates directories in my home directory

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#73]
When running the analysis system in the tutorial I noticed that the system creates three directories in my home directory at /turquoise/usr/projects/climate/akt
It created these directories:
20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison.test.pp
coupled_diagnostics_20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison-obs
coupled_diagnostics_20161117.beta0.A_WCYCL1850S.ne30_oEC_ICG.edison-obs.logs

This is very obnoxious behaviour since it will clutter my home directory.

**Comment by milenaveneziani** [comment]
Thanks @akturner, this is something that @xylar noticed too, and I agree that we should give the user the ability to save the output files in whatever directory they want (right now the $projdir directory is used for this, but that is also used for pointing to the observations and other things, so we should just add an output dir or something).

**Comment by xylar** [comment]
@milenaveneziani (cc @akturner), I don't think this is an issue that can be addressed in this repo.  It stems from the default behavior of the csh script created for LANL IC in the ACME PreAndPostProcessingScripts repo.  Therefore, I'm moving the issue to that repo.
