### ISSUE TITLE
Errors in Running Example from 2020 E3SM Tutorial on Cori

### ISSUE THREAD

**Issue by jasonlturner** [MPAS-Dev/MPAS-Analysis#731]
When following the latest tutorial for visualizing E3SM output ([tutorial page](https://mpas-dev.github.io/MPAS-Analysis/stable/tutorials/getting_started.html#purging-old-analysis), [tutorial video](https://www.youtube.com/watch?v=ljEYCR2ekD8&t=994s)), I encountered a few errors when using the observation data on Cori.  The following is the output from running _mpas_analysis --purge --verbose myrun.cfg_
![image](https://user-images.githubusercontent.com/46936542/92248006-a8528080-ee8d-11ea-8fd6-148bd5b38952.png)
![image](https://user-images.githubusercontent.com/46936542/92248132-d1731100-ee8d-11ea-8d8d-6dc414173a43.png)
Using _grep_ on the error logs yields
![image](https://user-images.githubusercontent.com/46936542/92248251-00898280-ee8e-11ea-83c4-f09f61f238f4.png)
There appears to be a mix of subprocess.CalledProcess errors, Key errors, and Permission errors.

In trying to resolve this, I downloaded the observation data and tried using that instead. When running _mpas_analysis --purge --verbose myrun.cfg_, I get the feedback
![image](https://user-images.githubusercontent.com/46936542/92249253-5e6a9a00-ee8f-11ea-8f6c-c7dc9daf93c4.png)
Using _grep_ on the error logs yields
![image](https://user-images.githubusercontent.com/46936542/92249303-76dab480-ee8f-11ea-9dc6-dd0b569b644e.png)
which appears to give only subprocess.CalledProcess errors, which I guess is progress of some sort?

If there is any other information I can provide, please let me know!

**Comment by xylar** [comment]
@jasonlturner, sorry things didn't work for you.  Thank you for reporting these problems.

I will try to look into them over the weekend or early next week.

**Comment by xylar** [comment]
@jasonlturner, following up a little sooner that I was planning to.

I think I fixed the permission issue with the file that was giving you trouble:
```
/global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/WOA18> ls -lah
total 7.2G
drwxrwx---  2 milena e3sm 4.0K May 21 01:32 .
drwxrwxr-x 16 milena e3sm 4.0K Aug 27  2019 ..
-rw-rw-r--  1 milena e3sm 1.7K Aug 30  2019 README.md
-rw-rw-r--  1 xylar  e3sm  751 Aug 30  2019 obs.bib
-rw-rw-r--  1 xylar  e3sm 1.6G May 20 11:41 woa18_ANN_T_S_z_vol_20200514.nc
-rw-rw-r--  1 xylar  e3sm 1.6G May 20 12:07 woa18_JAS_T_S_z_vol_20200514.nc
-rw-rw-r--  1 xylar  e3sm 1.6G May 20 12:33 woa18_JFM_T_S_z_vol_20200514.nc
-rw-rw-r--  1 xylar  e3sm 267M Aug 29  2019 woa18_decav_04_TS_ann_20190829.nc
-rw-rw-r--  1 xylar  e3sm 2.3G Aug 29  2019 woa18_decav_04_TS_mon_20190829.nc
```

I don't have permission to see your log files in your scratch directory.  Unfortunately, the grep message on its own isn't very helpful.  All I can tell is that `ncremap` is failing but the log file should have more information about why.  Could you share a log file here or change permissions so people from the `e3sm` group can access your output on scratch?

**Comment by xylar** [comment]
@jasonlturner, following up some more, could you see if you can run successfully after setting this environment variable?
```
export HDF5_USE_FILE_LOCKING=FALSE
```
We include this in the example job scripts for Cori here:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/master/configs/cori/job_script.cori-haswell.bash#L34
but I forgot to set it and I saw errors during setup that are similar to what you saw.

I will add setting this variable to the tutorial, as it does no harm that I am aware of even on systems that don't require it.

When I tried to test the analysis on Friday, I was also experiencing frequent hanging.  This seems to be a file system issue on Cori that I have seen with other python-based software at other times.  I don't have a good solution to it, other than to try again if you happen to see hanging on Cori.

I am now rerunning with the following steps:
```
salloc --partition=regular --qos=premium -C haswell --nodes=1 --time=3:00:00 --account=e3sm -L cscratch1,SCRATCH,project
source ~/miniconda3/etc/profile.d/conda.sh
conda activate mpas-analysis
export HDF5_USE_FILE_LOCKING=FALSE
mpas_analysis myrun.cfg --purge --verbose
```

It's still running but seems to be working fine for me.

If you would like to take a look, my version of the tutorial output on Cori is here:
/global/cscratch1/sd/xylar/mpas-analysis-tutorial

**Comment by jasonlturner** [comment]
Thank you for the quick follow-up! I attempted to re-run with the steps you most recently posted, using the diagnostic data available from /global/cfs/cdirs/e3sm/diagnostics and unfortunately received similar-looking errors.
![image](https://user-images.githubusercontent.com/46936542/92401605-9bcf6180-f0f3-11ea-893b-8c0eddbb1878.png)
![image](https://user-images.githubusercontent.com/46936542/92401626-a4c03300-f0f3-11ea-9feb-0e46bef29281.png)

I've attached the log files here: [jlturner_e3smdiags_logs.zip](https://github.com/MPAS-Dev/MPAS-Analysis/files/5183823/jlturner_e3smdiags_logs.zip)


I tried again using the diagnostic data I downloaded, and again received similar-looking errors 
![image](https://user-images.githubusercontent.com/46936542/92402537-56ac2f00-f0f5-11ea-8db5-747869e4e28d.png)

I've attached the log files here: 
[jlturner_downloadeddiags_logs.zip](https://github.com/MPAS-Dev/MPAS-Analysis/files/5183837/jlturner_downloadeddiags_logs.zip)

I've also attached my run config file here (I changed it to a .txt to attach it here, but it is still a .cfg on NERSC): [myrun.txt](https://github.com/MPAS-Dev/MPAS-Analysis/files/5183848/myrun.txt)

I also don't appear to have permission to view your version of the tutorial output at /global/cscratch1/sd/xylar/mpas-analysis-tutorial, nor any of the files in /global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/WOA18. 

If there is any other information I can provide, please let me know!

**Comment by xylar** [comment]
@jasonlturner, I think the problem has to be that you are not in the `e3sm` group.  If that's the case, you will, indeed, need to download the diagnostics data yourself.  I'll try to find out about the other error messages you're seeing once I get a chance to look at the log files.

Thanks for reporting back.  More soon.

**Comment by xylar** [comment]
Okay, so I'm trying to re-download all of the data in the `e3sm/diagnostics` directory that was not world readable (I don't have permission to change the permissions, so it's just easier to re-download.

It looks like the problem in the log files is that MPAS-Analysis can't find NCO (specifically `ncks`).  Did you follow all the instructions for downloading minoconda, installing it in your home directory and making an `mpas-analysis` environment?  It seems like your path from the log files indicates that the system Anaconda installation is in your path.  That suggest to me that you're using a different environment than the one in the tutorial, in which case things might not work.  At the very least, you may be getting interference between the system Anaconda and the miniconda environment you set up.  Could you let me know 1) exactly what modules are loaded when you just log in to Cori as normal; 2) exactly what procedure you followed to set up the miniconda environment for mpas-analysis; 3) exactly how you're running MPAS-Analysis (on a login node or a compute node) and what steps you take to get the job running and 4) exactly how your activating the conda environment, particularly if it's in a job script or an interactive job?  Something seems to be going wrong somewhere in that process.

**Comment by xylar** [comment]
@jasonlturner, I believe I had opened up permissions on all of the data you would need from `/global/cfs/cdirs/e3sm/diagnostics/` even if you are not in the `e3sm` group.  Please let me know if that still doesn't seem to be the case.

I'll await your response to my questions above to try to help figure out some next things to try.

Sorry this is proving pretty difficult.

**Comment by jasonlturner** [comment]
It's all good, I really appreciate all of the help you've been giving me!

1) When I log in to Cori normally, the following modules are loaded:
![image](https://user-images.githubusercontent.com/46936542/92414346-705f6d80-f119-11ea-9625-8fb7c5cdb522.png)

2) To set up the Miniconda environment for mpas-analysis, I did the following:

1. I created a subdirectory /global/cscratch1/sd/jlturner/mpas_tutorial, and downloaded the Miniconda3 installer (Miniconda3-latest-Linux-x86_64.sh) to that subdirectory.

2. I ran the command `/bin/bash Miniconda3-latest-Linux-x86_64.sh` with all of the default commands. It appears to have installed miniconda in the default location `~/miniconda3`. I said "no" to the prompt `Do you wish the installer to initialize Miniconda3 by running conda init? [yes|no]`.

3. To create the mpas-analysis environment, I ran the commands 
`$ source ~/miniconda3/etc/profile.d/conda.sh`
`$ conda config --add channels conda-forge`
`$ conda config --set channel_priority strict`
`$ conda create -n mpas-analysis python=3.8 mpas-analysis`
(I notice at this point that `python --version` states that I have Python 3.7.4 active, which may be relevant.)

3) I had been running mpas-analysis on a login node, until you instructed me to login to a compute node to run it with `salloc`. At least, I assume that's what that `salloc` command is doing.

4) To activate the mpas-analysis environment, I run the commands
`$ source ~/miniconda3/etc/profile.d/conda.sh`
`$ conda activate mpas-analysis`


I now appear to have access to /global/cfs/cdirs/e3sm/diagnostics/observations/Ocean/WOA18. I am also attempting to run the script again using the steps you mentioned in [your response above](https://github.com/MPAS-Dev/MPAS-Analysis/issues/731#issuecomment-688334432).

**Comment by xylar** [comment]
@jasonlturner, it sounds like you are doing everything right.  I don't see anything in your list of modules that suggests that the system python might be getting loaded and even if it were, the `conda activate` command should just override it.

What happens when you run `which ncks` once you have activated the `mpas-analysis` conda environment (preferably on a compute node after you have run `salloc`)?  I guess that will show a valid path.

Could you also tell me what is in your `$PATH` environment variable (again, after activating `mpas-analysis`) just in case that turns up any clues?

**Comment by jasonlturner** [comment]
@xylar The project I am on just ran out of compute hours, so I am unable to `salloc` to a compute node at this point in time. I am looking into getting access to more compute hours!

Activating `mpas-analysis` without using `salloc`, `which ncks` returns the file path 
`/global/homes/j/jlturner/miniconda3/envs/mpas-analysis/bin/ncks`
and my `$PATH` environment variable is (I added line-breaks to try to increase readability)
`/global/homes/j/jlturner/miniconda3/envs/mpas-analysis/bin:`
`/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin:`
`/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/condabin:/opt/cray/pe/mpt/7.7.10/gni/bin:`
`/opt/cray/rca/2.2.20-7.0.1.1_4.48__g8e3fb5b.ari/bin:`
`/opt/cray/alps/6.6.58-7.0.1.1_6.5__g437d88db.ari/sbin:`
`/opt/cray/alps/default/bin:`
`/opt/cray/job/2.2.4-7.0.1.1_3.37__g36b56f4.ari/bin:`
`/opt/cray/pe/craype/2.6.2/bin:`
`/opt/intel/compilers_and_libraries_2019.3.199/linux/bin/intel64:`
`/global/common/cori_cle7/software/darshan/3.1.7/bin:`
`/global/common/cori/software/altd/2.0/bin:`
`/usr/common/software/bin:`
`/usr/common/mss/bin:`
`/usr/common/nsg/bin:`
`/opt/ovis/bin:`
`/opt/ovis/sbin:`
`/opt/cray/pe/modules/3.2.11.4/bin:`
`/usr/local/bin:`
`/usr/bin:`
`/bin:`
`/usr/lib/mit/bin:`
`/usr/lib/mit/sbin:
`/opt/cray/pe/bin`

**Comment by xylar** [comment]
Okay, so it seems like something in your `.profile.ext` or `.bashrc.ext` is loading the system anaconda from `/global/common/cori_cle7/software/python/3.7-anaconda-2019.10`.  But not as a module.  Could you share the contents of your `.profile.ext` and `.bashrc.ext`?

Sorry this is taking so long.  I'm pretty baffled.

For reference, here are mine:
```
# begin .profile.ext

[ -e $HOME/.dbgdot ] && echo "entering .profile.ext"
#
# User additions to .profile go in this file
#
if [ -f /usr/common/usg/bin/nersc_host ]; then
  export NERSC_HOST=`/usr/common/usg/bin/nersc_host`
else
  export NERSC_HOST="unknown"
fi

if [ $NERSC_HOST == "davinci" ]
then
#  Replace the following line with personal settings for davinci
  touch /dev/null
fi

if [ $NERSC_HOST == "datatran" ]
then
#  Replace the following line with personal settings for datatran
  touch /dev/null
fi

[ -e $HOME/.dbgdot ] && echo "exiting .profile.ext"

# end .profile.ext
```

```
> cat .bashrc.ext
if [ -e /usr/common/usg/bin/nersc_host ]; then
  export NERSC_HOST=`/usr/common/usg/bin/nersc_host`
else
  export NERSC_HOST="unknown"
fi

if [ $NERSC_HOST == "cori" ]; then
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  export LESS=-R
  export SVN_EDITOR=vim
  module load git
  source ~/git-completion.bash
fi
```

By the way, be a bit careful about running MPAS-Analysis on login nodes.  I've gotten myself in trouble doing so.  I wouldn't run more than 4 tasks at a time and not use ncclimo in `bck` mode.

**Comment by xylar** [comment]
Also by the way, tripe back quotes are your friend!  Quoting text is a lot easier for me to read that screen shots and also I can copy and paste from it.

**Comment by jasonlturner** [comment]
I'd be happy to! I changed them to `.txt` files and attached them here:
[profile.ext.txt](https://github.com/MPAS-Dev/MPAS-Analysis/files/5191213/profile.ext.txt)
[bashrc.ext.txt](https://github.com/MPAS-Dev/MPAS-Analysis/files/5191214/bashrc.ext.txt)
I don't think I've ever opened these files before, so I'd be surprised if they were the cause!

I did make an alias in my `.profile` file awhile ago to make `cscratch1` change my current directory to my `cscratch1` directory. I deleted that, changed the run config file to use `serial` mode, and am attempting to re-run it. UPDATE: Same errors, darn!

It's all good that this is taking awhile! I bet it's a very complicated thing to work out, and I really appreciate all of the time and effort into helping me.

That makes sense! I will use triple quotes from now on.

**Comment by xylar** [comment]
Okay, well that didn't reveal anything (as I'm sure you realized).  

I am still trying to figure out how `/global/common/cori_cle7/software/python/3.7-anaconda-2019.10` is getting added to your path.  Can you grep for `anaconda` in all the files directly in your home directory and let me know if it turns up anything?

**Comment by jasonlturner** [comment]
Sure thing!

Using `grep anaconda ./.*` (since the only non-directory files I have in my home directory start with `.`), I got

```
(base) jlturner@cori12:~> grep anaconda ./.*
grep: ./.: Is a directory
grep: ./..: Is a directory
grep: ./.allinea: Is a directory
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.csh
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.csh
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
./.bash_history:source /global/cfs/cdirs/e3sm/software/anaconda_envs/load_latest_e3sm_unified.sh
./.bash_history:anaconda --version
./.bash_history:wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
./.bashrc:__conda_setup="$('/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
./.bashrc:    if [ -f "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/etc/profile.d/conda.sh" ]; then
./.bashrc:        . "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/etc/profile.d/conda.sh"
./.bashrc:        export PATH="/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin:$PATH"
grep: ./.cache: Is a directory
grep: ./.conda: Is a directory
grep: ./.config: Is a directory
grep: ./.dbus: Is a directory
grep: ./.globus: Is a directory
grep: ./.intel: Is a directory
grep: ./.ipynb_checkpoints: Is a directory
grep: ./.ipython: Is a directory
grep: ./.jupyter: Is a directory
./.kshrc:__conda_setup="$('/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
./.kshrc:    if [ -f "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/etc/profile.d/conda.sh" ]; then
./.kshrc:        . "/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/etc/profile.d/conda.sh"
./.kshrc:        export PATH="/global/common/cori_cle7/software/python/3.7-anaconda-2019.10/bin:$PATH"
grep: ./.local: Is a directory
grep: ./.ssh: Is a directory
grep: ./.uvcdat: Is a directory
grep: ./.vim: Is a directory
```

I'm guessing that's getting added to my path in the `./.kshrc` file! I have not idea what that file is for or how it got there, but I think the answer to that is only one Google search away.

**Comment by xylar** [comment]
If you're not intentionally using ksh, I would recommend switching to bash.  I don't think .kshrc will get loaded if you're not in ksh.  Id you prefer to stick with ksh, you should comment out this conda setup bit and see if that helps.  Maybe share your .kshrc in its entirety just to see if there might be other problems.

**Comment by jasonlturner** [comment]
I think I default to bash when I log in? A brief Google search told me I can check with the commands will
```
(base) jlturner@cori08:~> echo $SHELL
/bin/bash
(base) jlturner@cori08:~> echo $0
-bash
(base) jlturner@cori08:~> ps  -ef | grep $$ | grep -v grep
jlturner 57315 57314  0 10:39 pts/33   00:00:00 -bash
jlturner 64306 57315  0 10:40 pts/33   00:00:00 ps -ef
```

I commented out the relevant lines of the `.kshrc` file, logged out of NERSC, and logged back into NERSC. When I logged back in, I noticed that the `(base)` environment was not active. I am currently running the analysis, I will report back after!

**Comment by jasonlturner** [comment]
I believe everything ran properly! There aren't any errors in the output messages
```
(mpas-analysis) jlturner@cori08:/global/cscratch1/sd/jlturner/mpas_tutorial> mpas_analysis myrun.cfg --purge --verbose
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/plots
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/logs
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/clim/mpas
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/mapping
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/timeseries
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/html
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/masks
Deleting contents of /global/cscratch1/sd/jlturner/mpas_tutorial/output/clim/obs

running: /global/homes/j/jlturner/miniconda3/envs/mpas-analysis/bin/ESMF_RegridWeightGen --source /tmp/tmp3tbv_x56/src_mesh.nc --destination /tmp/tmp3tbv_x56/dst_mesh.nc --weight /global/cscratch1/sd/jlturner/mpas_tutorial/output/mapping/map_oQU480_to_0.5x0.5degree_bilinear.nc --method bilinear --netcdf4 --no_log --src_regional --ignore_unmapped
running: /global/homes/j/jlturner/miniconda3/envs/mpas-analysis/bin/ESMF_RegridWeightGen --source /tmp/tmpyy0t8_8b/src_mesh.nc --destination /tmp/tmpyy0t8_8b/dst_mesh.nc --weight /global/cscratch1/sd/jlturner/mpas_tutorial/output/mapping/map_oQU480_to_6000.0x6000.0km_10.0km_Antarctic_stereo_bilinear.nc --method bilinear --netcdf4 --no_log --src_regional --dst_regional --ignore_unmapped
Preprocessing SOSE transect data...
  temperature
  salinity
  potentialDensity
  zonalVelocity
  meridionalVelocity
  velMag
  Done.
running: /global/homes/j/jlturner/miniconda3/envs/mpas-analysis/bin/ESMF_RegridWeightGen --source /tmp/tmp1aah5iwt/src_mesh.nc --destination /tmp/tmp1aah5iwt/dst_mesh.nc --weight /global/cscratch1/sd/jlturner/mpas_tutorial/output/mapping/map_oQU480_to_SOSE_transects_5km_bilinear.nc --method bilinear --netcdf4 --no_log --src_regional --dst_regional --ignore_unmapped

Running tasks: 100% |#########################################################################################################################################################################################################################################| Time:  0:10:54

Log files for executed tasks can be found in /global/cscratch1/sd/jlturner/mpas_tutorial/output/logs
Total setup time: 0:02:31.81
Total run time: 0:13:26.62
Generating webpage for viewing results...
Done.
```

Are there other ways to verify it has worked?

**Comment by xylar** [comment]
Oh, great!  We finally figured it out.  That all looks right to me.

How strange with the `.kshrc`.  I'll have to file that one away as something that can interfere with bash.

I'm really relieved!

I'm going to close this but re-open if related troubles emerge.
