### ISSUE TITLE
Add SIV from GIOMAS?

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#742]
See Shu et al. (2015):  https://tc.copernicus.org/articles/9/399/2015/

**Comment by proteanplanet** [comment]
Hi @xylar, as an example of one model's realization of sea ice mass, it could be interesting, but this should not be something to 'aim' for.  The coupled sea ice configuration in E3SM is more advanced in almost every way.  The only reliable 'true' way to assess sea ice volume is with satellite emulation or with assimilation. But, as I say, if it's being presented as one model's realization, it won't hurt either.

**Comment by xylar** [comment]
Thanks @proteanplanet.  This came up in the poster session.  I figured it would be worth looking into.  I agree, we have to treat this like SOSE -- perhaps better than nothing to compare with but certainly not obs.

Would be happy to have something more sophisticated, for sure.
