### ISSUE TITLE
Improvement to delta OHC plot

### ISSUE THREAD

**Issue by golaz** [MPAS-Dev/MPAS-Analysis#766]
The delta OHC plot from MPAS-Analysis is extremely useful. But some of us tend to think in W/m2 (at TOA) rather than 1.e22 Joules (and I have a hard time converting between the two in my head). I'd like suggest adding slanted lines to the plot showing the conversion in W/m2 (total earth area) for easy comparions with netTOA in atmospheric plots.

Here is a mock-up of what such a plot might look like (I made up the numbers):

![ohc-suggested](https://user-images.githubusercontent.com/15743046/102436753-1ac71680-3fce-11eb-9e1a-32d936abdbdd.png)

**Comment by xylar** [comment]
@golaz, this is a really clever suggestion, very much appreciated.  Thank you for the mock-up as well.  That's very helpful.

I should be able to take care of this over the weekend and include it in the v1.3.0 release to be included in the E3SM-Unified release on Jan 1st.

**Comment by milenaveneziani** [comment]
yes, that would be a nice addition. A couple of details to consider:
1) would we calculate it as total trend over the full time series divided by the total Earth area? Probably the easiest thing to do.
2) I am afraid that 4 curves + 4 trend lines with associated trend values may make the plot too busy. Should we just do the trend for the top-to-bottom OHC curve?

**Comment by xylar** [comment]
@milenaveneziani, these are good thoughts but I interpret @golaz's idea a little differently. I don't think these are meant to be trend lines.  They're more like a second axis on the right-hand side, but converging to zero on the left.  The lines are just reference slopes and aren't related to any specific curve.  The number of lines would just be the number of tick marks you want to have on the right.

>

**Comment by milenaveneziani** [comment]
@xylar: the reason I thought @golaz meant to add actual trends is that this is what is done in the coupled diagnostics script that is used to generate this kind of plot (used a lot in WC tuning efforts), see last panel in particular:
![image](https://user-images.githubusercontent.com/8237579/102658910-bcb54300-4135-11eb-8146-71d2ebad17ef.png)

But anyways, I'll let Chris comment on this one.

**Comment by golaz** [comment]
Yes, as @xylar mentioned, this is really a second set of axes to interpret the plotted information differently. The best analogy I can think of are atmospheric Skew-T diagrams which have all sorts of skewed and even curved axes (for example, see https://en.wikipedia.org/wiki/Skew-T_log-P_diagram).
