### ISSUE TITLE
Remove dependency on meshfile in ocean_modelvsobs.py

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#77]
We no longer use the meshfile in ohc_timeseries to read in mesh-related information, but we rather look into the restart file. Therefore, we need to add a similar change in ocean_modelvsobs.

**Comment by xylar** [comment]
@milenaveneziani, I have a branch where I'm working on this.  I'll make a PR as soon as I've tested my changes.

**Comment by milenaveneziani** [comment]
Solved by #78.
