### ISSUE TITLE
Performance issue with oceanRegionalProfiles task

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/MPAS-Analysis#787]
On anvil, I have encountered the following error, when using 12 parallel tasks:
```
Compute time series of regional profiles...
analysis task oceanRegionalProfiles_computeOceanBasinsProfiles_0003-0003 failed during run
Traceback (most recent call last):
  File "/gpfs/fs1/home/ac.milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/shared/analysis_task.py", line 330, in run
    self.run_task()
  File "/gpfs/fs1/home/ac.milena/MPAS-git-repositories/MPAS-Analysis/mpas_analysis/ocean/ocean_regional_profiles.py", line 361, in run_task
    totalArea = (cellMasks * areaCell * vertMask).sum('nCells')
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/xarray/core/dataarray.py", line 2991, in func
    f(self.variable, other_variable)
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/xarray/core/variable.py", line 2301, in func
    f(self_data, other_data)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 3.43 GiB for an array with shape (9, 851664, 60) and data type float64
```

**Comment by darincomeau** [comment]
FWIW, the analysis for this mesh ran without issue for me with `parallelTaskCount = 6`.

**Comment by milenaveneziani** [comment]
Thanks @darincomeau: I have switched to 6 parallel tasks now.

**Comment by xylar** [comment]
Thanks @milenaveneziani for posting this.  That line seems ludicrously optimistic to me.  It is doing a giant computation on all regions, all cells and all vertical layers in one go.  I'm not sure what I was thinking...

Hopefully, this will be an easy thing to fix by adding a loop over regions and/or vertical levels.

**Comment by milenaveneziani** [comment]
Unrelated, but I thought I'd post it here for now: I also had to reduce the number of threads for ncclimo, as the default (12) was causing the Climatology task to fail. I now reduced it to 3, following Darin's choice, and crossing fingers.
I wonder if we shouldn't change the default to a smaller number.

**Comment by darincomeau** [comment]
@milenaveneziani sorry I should have included my other changes under [execute], which seems like is what you've just done:
`ncclimoParallelMode = bck
ncclimoThreads = 3`

**Comment by darincomeau** [comment]
I've run into this with the `WCAtl12to45E2r4` mesh (using my above settings with `ncclimoThreads = 3`), trying to run analysis on 80 years. From one of the `oceanRegionalProfiles_computeAntarcticRegionsProfiles_*` logs (there are a couple):

`MemoryError: Unable to allocate 4.95 GiB for an array with shape (851664, 13, 60) and data type float64`.

I'll just turn off that task for this particular analysis, but figured I'd report here.

**Comment by xylar** [comment]
Okay, I'll bump this up on my priority list...

**Comment by milenaveneziani** [comment]
@darincomeau: was the climatology going to be computed over 80 years?

**Comment by darincomeau** [comment]
@milenaveneziani no, only 10 years.

**Comment by milenaveneziani** [comment]
hmm, so your previous analysis over a different 10-year period ran fine with `ncclimoThreads = 3`, but the latest did not?

**Comment by xylar** [comment]
The `ncclimoThreads = 3` isn't relevant to this issue.

**Comment by xylar** [comment]
Only `parallelTaskCount` will affect this.  Some other tasks have a way to set `subprocessCount = 2` or something like that so they count as more than 1 task, but this isn't one of them.
