### ISSUE TITLE
IndoPacific MOC

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#789]
It looks as if the IndoPacific MOC is actually just the same plot as the Atlantic.  There must be some sort of indexing problem in the code.

https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.milena/20210326.v2beta3.piControl.ne30pg2_WCAtl12to45E2r4/testImproveTransectPerf/Years11-20/ocean/index.html#moc

![image](https://user-images.githubusercontent.com/4179064/113161315-8e6bf700-923e-11eb-8b08-35a0bfb834bb.png)
![image](https://user-images.githubusercontent.com/4179064/113161333-93c94180-923e-11eb-967c-2d2a9ce47931.png)

**Comment by xylar** [comment]
@milenaveneziani, I'll look into this when I have a chance but I want to fix the transport mask creation first.  If you happen to have time to look into this, that would be great!

**Comment by milenaveneziani** [comment]
good catch, @xylar!
This was introduced over the last month, as I ran the following analysis in February: https://compy-dtn.pnl.gov/vene705/E3SMv2alpha/mpas-analysis/20201108.alpha5_55_fallback.piControl.ne30pg2_r05_EC30to60E2r2-1900_ICG.compy/Test/ocean/index.html#moc
and the IndoPacific MOC is definitely different from the Atlantic MOC there.

For the record, that analysis was run using this MPAS-analysis version:
```
MPAS-Analysis version: 1.3.0

Git Hash: 3bdea91
```

**Comment by xylar** [comment]
It could be a problem with the mask file we're generating vs the one you were using then.  Worth making sure the mask NetCDF files look sane.

**Comment by milenaveneziani** [comment]
That's probably exactly what it is. The old transect files were called `SingleTransect` for a reason. I'll check them, perhaps as part of the work that will go into your changes of `MPAS-Tools` and `geometric_features`.
