### ISSUE TITLE
Modular Design

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#8]
The analysis framework should be designed and implemented in as modular a way as possible to improve the ability for other analyses to re-use portions of previous analyses.

**Comment by pwolfram** [comment]
This is obviously a moving target as we develop the analysis framework and #31 will help meet this requirement.

**Comment by milenaveneziani** [comment]
yeah, I am not even sure we should keep it as an open issue. We should instead make issues/tasks that we already have on the list of things to do and that ensure modularity as we move along (e.g., compute_climo module, interpolation module, etc).

**Comment by xylar** [comment]
@milenaveneziani I agree.  It isn't useful to have this as an issue, since it is unlikely to ever be "solved" completely.

**Comment by pwolfram** [comment]
Agreed.  I think we've already been making more specific issues as we go along anyway (e.g., #29)
