### ISSUE TITLE
Default config.analysis has un-useful default values

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#80]
The default values in the config.analysis are not especially useful for someone trying to start to use the system. The values are specific to one particular system and its unclear what things should be set to for a target machine. Does it make sense to make a new directory, say config_templates, and then a set of default config files for machine we use:
config.lanl_ice
config.lanl_ice_seaice_standalone
config.edison
etc ?

**Comment by milenaveneziani** [comment]
yeah, this is a good idea. Maybe we can have some config_templates in the configuration directory?

**Comment by pwolfram** [comment]
I chatted with @akturner about this idea earlier and I think that is a great idea.

**Comment by pwolfram** [comment]
We should provide good examples for different platforms following resolution of #86 in particular.

**Comment by xylar** [comment]
Agreed.  I figured that would be the logical progression.  First the reorganization in #86, then use the resulting template to create useful examples for different machines.

**Comment by xylar** [comment]
This has been addressed by #86
