### ISSUE TITLE
Add SSH time series plot

### ISSUE THREAD

**Issue by golaz** [MPAS-Dev/MPAS-Analysis#811]
I'd like to suggest to add a time series plot for SSH as an easy way to spot obvious non-conservation issues. We ran into undetected SSH drifts during both v1 and v2 model development.

**Comment by xylar** [comment]
@golaz, you just want the global mean SSH?

**Comment by maltrud** [comment]
@xylar , i think the most useful metric would be the change in ocean volume relative to t=0, then divided by the surface area of the ocean.

**Comment by xylar** [comment]
@maltrud, isn't that identical to the change in global mean SSH from the initial condition? Since we don't let the surface area (or the bathymetry) change in time.

**Comment by xylar** [comment]
@maltrud, your suggestion was a good one, since we already have the total ocean volume and area in `timeSeriesStatsMonthly`.  The ratio is the mean water-column thickness, and the anomaly in mean water-column thickness is the same as the anomaly in SSH for a fixed ocean area.

**Comment by golaz** [comment]
@xylar  and @maltrud : you can decide which variable is best between volume or SSH. It would be useful to have some global, annual mean variable that can tell us about possible water non-conservation.
