### ISSUE TITLE
Updating the namelist for chlorophyll

### ISSUE THREAD

**Issue by ytakano3** [MPAS-Dev/MPAS-Analysis#825]
I ran into an issue comparing two MPAS-O BGC simulations, seems like there is an update in the name of chlorophyll in the recent model. We need to change the variable name for chlorophyll from "timeMonthly_avg_ecosysTracers_Chl" to new variable names. A bit complicated part is that now we have 4 components, 

"timeMonthly_avg_ecosysTracers_diatChl", 
"timeMonthly_avg_ecosysTracers_diazChl", 
"timeMonthly_avg_ecosysTracers_phaeoChl", and 
"timeMonthly_avg_ecosysTracers_spChl

... so we need add these 4 components to obtain the total Chl. This has been done when I run MPAS-Analysis comparing between the simulation and observation (in the MPAS-Analysis results, I see a new variable name "Chl" is generated) but does not work when we compare two simulations (control vs main). It will be great if I can get support fixing this issue.

**Comment by xylar** [comment]
Thanks for posting this, @ytakano3.  @bradyrx wrote the original analysis so I'll have to get myself up to speed on how chlorophyll in particular was handled to see how the problem emerges.  I don't think this will be hard to fix.

**Comment by ytakano3** [comment]
@xylar Thank you, please keep us updated.
