### ISSUE TITLE
Convert namelist to dict function not working for datm_in

### ISSUE THREAD

**Issue by changliao1025** [MPAS-Dev/MPAS-Analysis#871]
It seems that the datm namelist file is not formatted friendly for the `convert_namelist_to_dict(fname, readonly=True) `function.

```
&shr_strdata_nml
  datamode = "CLMNCEP"
  domainfile = "somepath"
  dtlimit = 1.5, 1.5, 1.5, 1.5, 1.5
  fillalgo = "nn", "nn", "nn", "nn", "nn"
  fillmask = "nomask", "nomask", "nomask", "nomask", "nomask"
  fillread = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
  fillwrite = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
  mapalgo = "bilinear", "bilinear", "bilinear", "bilinear", "bilinear"
  mapmask = "nomask", "nomask", "nomask", "nomask", "nomask"
  mapread = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
  mapwrite = "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET"
  readmode = "single", "single", "single", "single", "single"
  streams = "datm.streams.txt.CLMGSWP3v1.Solar 1950 1950 2010",
      "datm.streams.txt.CLMGSWP3v1.Precip 1950 1950 2010",
      "datm.streams.txt.CLMGSWP3v1.TPQW 1950 1950 2010",
      "datm.streams.txt.presaero.clim_2000 1 1 1",
      "datm.streams.txt.topo.observed 1 1 1"
  taxmode = "cycle", "cycle", "cycle", "cycle", "cycle"
  tintalgo = "coszen", "nearest", "linear", "linear", "lower"
  vectors = "null"
```

This function returns a single value for the streams key:
```
'fillmask':'nomask", "nomask", "nomask", "nomask", "nomask'
'fillread':'NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET'
'fillwrite':'NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET'
'mapalgo':'bilinear", "bilinear", "bilinear", "bilinear", "bilinear'
'mapmask':'nomask", "nomask", "nomask", "nomask", "nomask'
'mapread':'NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET'
'mapwrite':'NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET", "NOT_SET'
'readmode':'single", "single", "single", "single", "single'
'streams':'datm.streams.txt.CLMGSWP3v1.Solar 1950 1950 2010",'
'taxmode':'cycle", "cycle", "cycle", "cycle", "cycle'
'tintalgo':'coszen", "nearest", "linear", "linear", "lower'
'vectors':'null'
```

I think the breakline is preventing the correct parsering. 
Note that only the "datm.streams.txt.CLMGSWP3v1.Solar 1950 1950 2010" was retrieved. 
@xylar

**Comment by xylar** [comment]
@changliao1025, I'm a bit confused about what you would like to do.

MPAS-Analysis is provide analysis for MPAS-Ocean and MPAS-Seaice data only, not EAM (or `datm`).  Were you hoping to use a subset of our functionality to parse other namelists?  I'm afraid we do not have any intention of parsing all namelists, just those from MPAS components.

**Comment by xylar** [comment]
@changliao1025, thanks for the reminder on Slack that I recommended you use this.  I forgot.

Could you point me to the original namelist file you're trying to parse?  The formatting here didn't come through.

Also, if you use triple-back quotes (```), you can get the effect I think you were after above.

**Comment by xylar** [comment]
I fixed the formatting above.  I should be able to work with this now.

**Comment by changliao1025** [comment]
Yes, this is an atm name list from a E3SM case. I only extracted this function and it works in other applications. But I recently got an error when dealing with the atm name list. I wrote another function to preprocess the name list file so it is compatible.

**Comment by xylar** [comment]
I happen to have been looking at code for parsing config files with multiline config options recently and the problem is nearly identical.  I'll try to fix it in the next few days.

**Comment by changliao1025** [comment]
Well, that is interesting! I didn't search that, but I just wrote an updated function to "glue" those lines back so the original function still works. I bet you can add this package as a dependency? @xylar
