### ISSUE TITLE
Design Document: Generalized Horizontal Interpolation

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#88]
<h1> Title: Generalized Nearest-neighbor and First-order Interpolation in MPAS-Analysis <br>
Xylar Asay-Davis <br>
date: 01-19-2017 <br>
</h1>
<h2> Summary </h2>
Many types of analysis in MPAS will require fields that are interpolated from MPAS grids to arbitrary points.  Currently, nearest-neighbor interpolation is supported in MPAS-Analysis, but only for points on a uniformly spaced lat-lon grid.  Building on the existing approach, this design document describes methods for performing both nearest-neighbor and first-order (linear or similar) interpolation from MPAS grids to arbitrary points.

<h1> Requirements </h1>
<h2>Requirement: Support for arbitrary output interpolation points
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis
</h2>

The calling code should be able to supply any desired interpolation points, not just a regular latitude-longitude grid.

<h2>Requirement: Cartesian input mesh
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis
</h2>

The source mesh should be described in Cartesian, rather than lon-lat, space.  This is more consistent with how MPAS meshes are constructed (e.g. they have Voronoi cells only in Cartesian coordinates, not in lon-lat coordinates) and also is more conducive to supporting both spherical and planar meshes.

<h2>Requirement: First-order interpolation
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis</h2>

The option to interpolate smoothly (e.g. linearly or with barycentric coordinates) between cell-centered values should be added.  The calling code should easily be able to select either nearest-neighbor or first-order interpolation with a flag as part of the initialization step is required and from then on should not need to keep track of which method is being used.

<h2>Requirement: Interpolation should handle periodic boundaries
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis</h2>

Interpolation code should be aware of periodic boundaries and should perform interpolation that is consistent with those boundaries.

<h2>Consideration: Support caching results from any costly, one-time geometric computations
Date last modified: 2017/01/20
Contributors: Xylar Asay-Davis</h2>

For many potential algorithms used to perform interpolation, there is likely to be a relatively costly step of computing fields such as indices into input data fields and interpolation weights that 1) only need to be computed once for a given input mesh and set of output points and 2) are independent of the data in the field being interpolated.  If this data were cached, it could mean that rerunning the analysis (which might be very desirable, e.g., while monitoring the progress of a run) would be much cheaper than the initial run.

<h1> Algorithmic Formulations </h1>
<h2>Design solution: Support for arbitrary output interpolation points
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis</h2>

The calling code will be required to supply the interpolation points in cartesian space instead of supplying lon-lat bounds and steps.  This will allow greater generality.  A helper function will be provided that can produce a regularly spaced lon-lat grid.  Another helper function (lon_lat_to_cartesian) is already available for converting from lon-lat to Cartesian space.  Note: code calling using this helper function should use the spherical radius from an MPAS restart or input file instead of using the default value.
The KD tree method currently used for nearest-neighbor interpolation does not care about how the interpolation points are spaced and thus will remain largely unchanged.

<h2>Design solution: Cartesian input mesh
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis</h2>

Currently, lonCell and latCell are passed as input arguments.  For efficiency, it would make more sense to use xCell, yCell, zCell rather than lonCell and latCell.  (Currently, fields equivalent to xCell, yCell and zCell are being computed from lonCell and latCell in the nearest neighbor code.)  Moreover, to support more generality in the interpolation algorithm (see next design solution), it may be best to pass an xarray data set containing xCell, yCell and zCell but also other mesh variables needed for linear interpolation.

<h2>Design solution: First-order interpolation
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis</h2>

Linear interpolation will require locations of MPAS mesh cells, vertices and a list of cellsOnVertex.  Therefore, it seems simplest if the routine for initializing interpolation takes an MPAS mesh data set as an input argument, from which it can read whichever geometric information is needed for interpolation.
The output of the initialization routine (for either linear or nearest-neighbor interpolation) will be a 2D array of MPAS cell indices and corresponding interpolation weights.  The first dimension in each array corresponds to the output interpolation points.  The second index is over input cells neighboring the output point (either a single entry for nearest-neighbor or vertexDegree entries for linear).
The algorithm for linear interpolation will be as follows:
Store the shape of the array of output points
Use a KD tree method (the same currently used to find nearest neighboring cells) to find nearest neighboring vertices to each output point
For each output point at (xp, yp, zp), the interpolation weight for each neighboring cell is given by barycentric weights (e.g. http://answers.unity3d.com/questions/383804/calculate-uv-coordinates-of-3d-point-on-plane-of-m.html).  If only 2 neighboring cells are available, linear interpolation based on distance between the cells should be used instead.  If only one neighboring cell exists, the weight of that cell is (obviously) 1.  Note: if we want to support vertexDegree = 4, we would need to either use Wachspress coordinates or divide each quadrilateral into 2 triangles.
Store the indices and weights for interpolating arbitrarily many fields
For each field, interpolation is as simple as indexing the field at the given indices, multiplying by the weights, summing over neighbors, and reshaping the field to conform to the shape stored in step 1.
It will likely be desirable to create an Interpolator class that keeps track of the indices, weights and output shape so these don't need to be stored or passed in later as input arguments.  This approach is also consistent with how scipy handles interpolation (https://docs.scipy.org/doc/scipy-0.18.1/reference/interpolate.html)

<h2>Design solution: Interpolation should handle periodic boundaries
Date last modified: 2017/01/19
Contributors: Xylar Asay-Davis</h2>

My first instinct is that we typically use smaller meshes when we use periodic boundaries, meaning it might be feasible to just make periodic copies of the mesh variables.  This is what I have typically done to support periodic mesh computations in POP.  For now, this is largely just a placeholder until I can give this some more thought.

<h1> Design and Implementation </h1>
<h2> Implementation: short-desciption-of-implementation-here <br>
Date last modified: 2011/01/05 <br>
Contributors: (add your name to this list if it does not appear)
</h2>

This section should detail the plan for implementing the design solution for requirement XXX. In general, this section is software-centric with a focus on software implementation. Pseudo code is appropriate in this section. Links to actual source code are appropriate. Project management items, such as svn branches, timelines and staffing are also appropriate. How do we typeset pseudo code?

<h1> Testing </h1>
<h2> Testing and Validation: short-desciption-of-testing-here <br>
Date last modified: 2011/01/05 <br>
Contributors: (add your name to this list if it does not appear)
</h2>

How will XXX be tested? i.e. how will be we know when we have met requirement XXX. Will these unit tests be included in the ongoing going forward?

For those with access to the ACME Confluence pages, see the following for more discussion:
https://acme-climate.atlassian.net/wiki/display/OCNICE/Analysis+-+Generalized+Nearest-neighbor+and+Linear+Interpolation

**Comment by xylar** [comment]
This is a test to see if creating an issue is a good way of posting a design document for discussion in this repo.

**Comment by xylar** [comment]
If we decide to do this, I will add a new label "design doc".

**Comment by pwolfram** [comment]
I added the label, which we would need for a PR-based approach anyway.  However, I think we really need a PR so that I can easily highlight changes on a line-by-line basic for discussion.  The issue format doesn't appear to provide this functionality unless I'm missing something.

**Comment by xylar** [comment]
Closing this issue and moving to #90 (a PR insead).
