### ISSUE TITLE
Inconsistencies in SSS values?

### ISSUE THREAD

**Issue by alicebarthel** [MPAS-Dev/MPAS-Analysis#938]
@xylar @milenaveneziani I ran MPAS-Analysis on a short simulation and the colorplots for SSS seem to disagree (e.g. look at [SSS-Aquarius ](https://compy-dtn.pnl.gov/bart765/E3SMv2/20221202.v2_1.impacts.uniformIC.ne30pg2_EC30to60E2r2.compy/20221202.v2_1.impacts.uniformIC.ne30pg2_EC30to60E2r2.compy/mpas_analysis/ts_0001-0001_climo_0001-0001/ocean/index.html#global_sss&gid=3&pid=3)plot <28; and [Salinity-WOA](https://compy-dtn.pnl.gov/bart765/E3SMv2/20221202.v2_1.impacts.uniformIC.ne30pg2_EC30to60E2r2.compy/20221202.v2_1.impacts.uniformIC.ne30pg2_EC30to60E2r2.compy/mpas_analysis/ts_0001-0001_climo_0001-0001/ocean/index.html#global_sss&gid=10&pid=1) ~34.5psu. ) I did not know it was possible for these to fetch/return different values. I will look into it but opening an issue so it does not fall off my radar.

**Comment by alicebarthel** [comment]
Similarly, the min-mean-max values are off (inconsistent and mean<min). Maybe something wrong with the masking..?
![Screen Shot 2022-12-13 at 3 13 37 PM](https://user-images.githubusercontent.com/36741014/207456024-f18dcdb9-d4a1-4ff7-a1c3-c7f5f9c8f0c2.png)

![Screen Shot 2022-12-13 at 3 13 50 PM](https://user-images.githubusercontent.com/36741014/207456000-60ec33a5-0ccb-4e5c-b88a-0a3b3ac6504e.png)

**Comment by milenaveneziani** [comment]
Looking at the plots you posted, it seems to me that something is wrong with the model results for the Aquarius comparison, where model data is mostly 1.331e-6..
Really not sure what is going on, I have never seen it...

**Comment by milenaveneziani** [comment]
These are definitely not the real model results..:

![image](https://user-images.githubusercontent.com/8237579/207465167-19f36883-881f-4628-93d6-45d6d869c3d1.png)

**Comment by xylar** [comment]
@alicebarthel, is this an ongoing concern?  I think the issue may have been specific to the run you were analyzing.  If it's still a problem, please point me to the machine and analysis directory.
